package com.google.android.gms.internal.mlkit_common;

import com.google.firebase.encoders.FieldDescriptor;
import com.google.firebase.encoders.ObjectEncoder;
import com.google.firebase.encoders.ObjectEncoderContext;
import java.io.IOException;
/* loaded from: classes8.dex */
public final class b3 implements ObjectEncoder {
    public static final FieldDescriptor A;
    public static final FieldDescriptor A0;
    public static final FieldDescriptor B;
    public static final FieldDescriptor B0;
    public static final FieldDescriptor C;
    public static final FieldDescriptor C0;
    public static final FieldDescriptor D;
    public static final FieldDescriptor D0;
    public static final FieldDescriptor E;
    public static final FieldDescriptor E0;
    public static final FieldDescriptor F;
    public static final FieldDescriptor F0;
    public static final FieldDescriptor G;
    public static final FieldDescriptor G0;
    public static final FieldDescriptor H;
    public static final FieldDescriptor H0;
    public static final FieldDescriptor I;
    public static final FieldDescriptor I0;
    public static final FieldDescriptor J;
    public static final FieldDescriptor J0;
    public static final FieldDescriptor K;
    public static final FieldDescriptor K0;
    public static final FieldDescriptor L;
    public static final FieldDescriptor L0;
    public static final FieldDescriptor M;
    public static final FieldDescriptor M0;
    public static final FieldDescriptor N;
    public static final FieldDescriptor N0;
    public static final FieldDescriptor O;
    public static final FieldDescriptor O0;
    public static final FieldDescriptor P;
    public static final FieldDescriptor P0;
    public static final FieldDescriptor Q;
    public static final FieldDescriptor Q0;
    public static final FieldDescriptor R;
    public static final FieldDescriptor R0;
    public static final FieldDescriptor S;
    public static final FieldDescriptor S0;
    public static final FieldDescriptor T;
    public static final FieldDescriptor T0;
    public static final FieldDescriptor U;
    public static final FieldDescriptor U0;
    public static final FieldDescriptor V;
    public static final FieldDescriptor V0;
    public static final FieldDescriptor W;
    public static final FieldDescriptor W0;
    public static final FieldDescriptor X;
    public static final FieldDescriptor X0;
    public static final FieldDescriptor Y;
    public static final FieldDescriptor Y0;
    public static final FieldDescriptor Z;
    public static final FieldDescriptor Z0;

    /* renamed from: a  reason: collision with root package name */
    public static final b3 f9165a = new b3();
    public static final FieldDescriptor a0;
    public static final FieldDescriptor a1;
    public static final FieldDescriptor b;
    public static final FieldDescriptor b0;
    public static final FieldDescriptor b1;
    public static final FieldDescriptor c;
    public static final FieldDescriptor c0;
    public static final FieldDescriptor c1;
    public static final FieldDescriptor d;
    public static final FieldDescriptor d0;
    public static final FieldDescriptor e;
    public static final FieldDescriptor e0;
    public static final FieldDescriptor f;
    public static final FieldDescriptor f0;
    public static final FieldDescriptor g;
    public static final FieldDescriptor g0;
    public static final FieldDescriptor h;
    public static final FieldDescriptor h0;
    public static final FieldDescriptor i;
    public static final FieldDescriptor i0;
    public static final FieldDescriptor j;
    public static final FieldDescriptor j0;
    public static final FieldDescriptor k;
    public static final FieldDescriptor k0;
    public static final FieldDescriptor l;
    public static final FieldDescriptor l0;
    public static final FieldDescriptor m;
    public static final FieldDescriptor m0;
    public static final FieldDescriptor n;
    public static final FieldDescriptor n0;
    public static final FieldDescriptor o;
    public static final FieldDescriptor o0;
    public static final FieldDescriptor p;
    public static final FieldDescriptor p0;
    public static final FieldDescriptor q;
    public static final FieldDescriptor q0;
    public static final FieldDescriptor r;
    public static final FieldDescriptor r0;
    public static final FieldDescriptor s;
    public static final FieldDescriptor s0;
    public static final FieldDescriptor t;
    public static final FieldDescriptor t0;
    public static final FieldDescriptor u;
    public static final FieldDescriptor u0;
    public static final FieldDescriptor v;
    public static final FieldDescriptor v0;
    public static final FieldDescriptor w;
    public static final FieldDescriptor w0;
    public static final FieldDescriptor x;
    public static final FieldDescriptor x0;
    public static final FieldDescriptor y;
    public static final FieldDescriptor y0;
    public static final FieldDescriptor z;
    public static final FieldDescriptor z0;

    static {
        FieldDescriptor.Builder builder = FieldDescriptor.builder("systemInfo");
        zzbk zzbkVar = new zzbk();
        zzbkVar.zza(1);
        b = builder.withProperty(zzbkVar.zzb()).build();
        FieldDescriptor.Builder builder2 = FieldDescriptor.builder("eventName");
        zzbk zzbkVar2 = new zzbk();
        zzbkVar2.zza(2);
        c = builder2.withProperty(zzbkVar2.zzb()).build();
        FieldDescriptor.Builder builder3 = FieldDescriptor.builder("isThickClient");
        zzbk zzbkVar3 = new zzbk();
        zzbkVar3.zza(37);
        d = builder3.withProperty(zzbkVar3.zzb()).build();
        FieldDescriptor.Builder builder4 = FieldDescriptor.builder("clientType");
        zzbk zzbkVar4 = new zzbk();
        zzbkVar4.zza(61);
        e = builder4.withProperty(zzbkVar4.zzb()).build();
        FieldDescriptor.Builder builder5 = FieldDescriptor.builder("modelDownloadLogEvent");
        zzbk zzbkVar5 = new zzbk();
        zzbkVar5.zza(3);
        f = builder5.withProperty(zzbkVar5.zzb()).build();
        FieldDescriptor.Builder builder6 = FieldDescriptor.builder("customModelLoadLogEvent");
        zzbk zzbkVar6 = new zzbk();
        zzbkVar6.zza(20);
        g = builder6.withProperty(zzbkVar6.zzb()).build();
        FieldDescriptor.Builder builder7 = FieldDescriptor.builder("customModelInferenceLogEvent");
        zzbk zzbkVar7 = new zzbk();
        zzbkVar7.zza(4);
        h = builder7.withProperty(zzbkVar7.zzb()).build();
        FieldDescriptor.Builder builder8 = FieldDescriptor.builder("customModelCreateLogEvent");
        zzbk zzbkVar8 = new zzbk();
        zzbkVar8.zza(29);
        i = builder8.withProperty(zzbkVar8.zzb()).build();
        FieldDescriptor.Builder builder9 = FieldDescriptor.builder("onDeviceFaceDetectionLogEvent");
        zzbk zzbkVar9 = new zzbk();
        zzbkVar9.zza(5);
        j = builder9.withProperty(zzbkVar9.zzb()).build();
        FieldDescriptor.Builder builder10 = FieldDescriptor.builder("onDeviceFaceLoadLogEvent");
        zzbk zzbkVar10 = new zzbk();
        zzbkVar10.zza(59);
        k = builder10.withProperty(zzbkVar10.zzb()).build();
        FieldDescriptor.Builder builder11 = FieldDescriptor.builder("onDeviceTextDetectionLogEvent");
        zzbk zzbkVar11 = new zzbk();
        zzbkVar11.zza(6);
        l = builder11.withProperty(zzbkVar11.zzb()).build();
        FieldDescriptor.Builder builder12 = FieldDescriptor.builder("onDeviceTextDetectionLoadLogEvent");
        zzbk zzbkVar12 = new zzbk();
        zzbkVar12.zza(79);
        m = builder12.withProperty(zzbkVar12.zzb()).build();
        FieldDescriptor.Builder builder13 = FieldDescriptor.builder("onDeviceBarcodeDetectionLogEvent");
        zzbk zzbkVar13 = new zzbk();
        zzbkVar13.zza(7);
        n = builder13.withProperty(zzbkVar13.zzb()).build();
        FieldDescriptor.Builder builder14 = FieldDescriptor.builder("onDeviceBarcodeLoadLogEvent");
        zzbk zzbkVar14 = new zzbk();
        zzbkVar14.zza(58);
        o = builder14.withProperty(zzbkVar14.zzb()).build();
        FieldDescriptor.Builder builder15 = FieldDescriptor.builder("onDeviceImageLabelCreateLogEvent");
        zzbk zzbkVar15 = new zzbk();
        zzbkVar15.zza(48);
        p = builder15.withProperty(zzbkVar15.zzb()).build();
        FieldDescriptor.Builder builder16 = FieldDescriptor.builder("onDeviceImageLabelLoadLogEvent");
        zzbk zzbkVar16 = new zzbk();
        zzbkVar16.zza(49);
        q = builder16.withProperty(zzbkVar16.zzb()).build();
        FieldDescriptor.Builder builder17 = FieldDescriptor.builder("onDeviceImageLabelDetectionLogEvent");
        zzbk zzbkVar17 = new zzbk();
        zzbkVar17.zza(18);
        r = builder17.withProperty(zzbkVar17.zzb()).build();
        FieldDescriptor.Builder builder18 = FieldDescriptor.builder("onDeviceObjectCreateLogEvent");
        zzbk zzbkVar18 = new zzbk();
        zzbkVar18.zza(26);
        s = builder18.withProperty(zzbkVar18.zzb()).build();
        FieldDescriptor.Builder builder19 = FieldDescriptor.builder("onDeviceObjectLoadLogEvent");
        zzbk zzbkVar19 = new zzbk();
        zzbkVar19.zza(27);
        t = builder19.withProperty(zzbkVar19.zzb()).build();
        FieldDescriptor.Builder builder20 = FieldDescriptor.builder("onDeviceObjectInferenceLogEvent");
        zzbk zzbkVar20 = new zzbk();
        zzbkVar20.zza(28);
        u = builder20.withProperty(zzbkVar20.zzb()).build();
        FieldDescriptor.Builder builder21 = FieldDescriptor.builder("onDevicePoseDetectionLogEvent");
        zzbk zzbkVar21 = new zzbk();
        zzbkVar21.zza(44);
        v = builder21.withProperty(zzbkVar21.zzb()).build();
        FieldDescriptor.Builder builder22 = FieldDescriptor.builder("onDeviceSegmentationLogEvent");
        zzbk zzbkVar22 = new zzbk();
        zzbkVar22.zza(45);
        w = builder22.withProperty(zzbkVar22.zzb()).build();
        FieldDescriptor.Builder builder23 = FieldDescriptor.builder("onDeviceSmartReplyLogEvent");
        zzbk zzbkVar23 = new zzbk();
        zzbkVar23.zza(19);
        x = builder23.withProperty(zzbkVar23.zzb()).build();
        FieldDescriptor.Builder builder24 = FieldDescriptor.builder("onDeviceLanguageIdentificationLogEvent");
        zzbk zzbkVar24 = new zzbk();
        zzbkVar24.zza(21);
        y = builder24.withProperty(zzbkVar24.zzb()).build();
        FieldDescriptor.Builder builder25 = FieldDescriptor.builder("onDeviceTranslationLogEvent");
        zzbk zzbkVar25 = new zzbk();
        zzbkVar25.zza(22);
        z = builder25.withProperty(zzbkVar25.zzb()).build();
        FieldDescriptor.Builder builder26 = FieldDescriptor.builder("cloudFaceDetectionLogEvent");
        zzbk zzbkVar26 = new zzbk();
        zzbkVar26.zza(8);
        A = builder26.withProperty(zzbkVar26.zzb()).build();
        FieldDescriptor.Builder builder27 = FieldDescriptor.builder("cloudCropHintDetectionLogEvent");
        zzbk zzbkVar27 = new zzbk();
        zzbkVar27.zza(9);
        B = builder27.withProperty(zzbkVar27.zzb()).build();
        FieldDescriptor.Builder builder28 = FieldDescriptor.builder("cloudDocumentTextDetectionLogEvent");
        zzbk zzbkVar28 = new zzbk();
        zzbkVar28.zza(10);
        C = builder28.withProperty(zzbkVar28.zzb()).build();
        FieldDescriptor.Builder builder29 = FieldDescriptor.builder("cloudImagePropertiesDetectionLogEvent");
        zzbk zzbkVar29 = new zzbk();
        zzbkVar29.zza(11);
        D = builder29.withProperty(zzbkVar29.zzb()).build();
        FieldDescriptor.Builder builder30 = FieldDescriptor.builder("cloudImageLabelDetectionLogEvent");
        zzbk zzbkVar30 = new zzbk();
        zzbkVar30.zza(12);
        E = builder30.withProperty(zzbkVar30.zzb()).build();
        FieldDescriptor.Builder builder31 = FieldDescriptor.builder("cloudLandmarkDetectionLogEvent");
        zzbk zzbkVar31 = new zzbk();
        zzbkVar31.zza(13);
        F = builder31.withProperty(zzbkVar31.zzb()).build();
        FieldDescriptor.Builder builder32 = FieldDescriptor.builder("cloudLogoDetectionLogEvent");
        zzbk zzbkVar32 = new zzbk();
        zzbkVar32.zza(14);
        G = builder32.withProperty(zzbkVar32.zzb()).build();
        FieldDescriptor.Builder builder33 = FieldDescriptor.builder("cloudSafeSearchDetectionLogEvent");
        zzbk zzbkVar33 = new zzbk();
        zzbkVar33.zza(15);
        H = builder33.withProperty(zzbkVar33.zzb()).build();
        FieldDescriptor.Builder builder34 = FieldDescriptor.builder("cloudTextDetectionLogEvent");
        zzbk zzbkVar34 = new zzbk();
        zzbkVar34.zza(16);
        I = builder34.withProperty(zzbkVar34.zzb()).build();
        FieldDescriptor.Builder builder35 = FieldDescriptor.builder("cloudWebSearchDetectionLogEvent");
        zzbk zzbkVar35 = new zzbk();
        zzbkVar35.zza(17);
        J = builder35.withProperty(zzbkVar35.zzb()).build();
        FieldDescriptor.Builder builder36 = FieldDescriptor.builder("automlImageLabelingCreateLogEvent");
        zzbk zzbkVar36 = new zzbk();
        zzbkVar36.zza(23);
        K = builder36.withProperty(zzbkVar36.zzb()).build();
        FieldDescriptor.Builder builder37 = FieldDescriptor.builder("automlImageLabelingLoadLogEvent");
        zzbk zzbkVar37 = new zzbk();
        zzbkVar37.zza(24);
        L = builder37.withProperty(zzbkVar37.zzb()).build();
        FieldDescriptor.Builder builder38 = FieldDescriptor.builder("automlImageLabelingInferenceLogEvent");
        zzbk zzbkVar38 = new zzbk();
        zzbkVar38.zza(25);
        M = builder38.withProperty(zzbkVar38.zzb()).build();
        FieldDescriptor.Builder builder39 = FieldDescriptor.builder("isModelDownloadedLogEvent");
        zzbk zzbkVar39 = new zzbk();
        zzbkVar39.zza(39);
        N = builder39.withProperty(zzbkVar39.zzb()).build();
        FieldDescriptor.Builder builder40 = FieldDescriptor.builder("deleteModelLogEvent");
        zzbk zzbkVar40 = new zzbk();
        zzbkVar40.zza(40);
        O = builder40.withProperty(zzbkVar40.zzb()).build();
        FieldDescriptor.Builder builder41 = FieldDescriptor.builder("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzbk zzbkVar41 = new zzbk();
        zzbkVar41.zza(30);
        P = builder41.withProperty(zzbkVar41.zzb()).build();
        FieldDescriptor.Builder builder42 = FieldDescriptor.builder("aggregatedCustomModelInferenceLogEvent");
        zzbk zzbkVar42 = new zzbk();
        zzbkVar42.zza(31);
        Q = builder42.withProperty(zzbkVar42.zzb()).build();
        FieldDescriptor.Builder builder43 = FieldDescriptor.builder("aggregatedOnDeviceFaceDetectionLogEvent");
        zzbk zzbkVar43 = new zzbk();
        zzbkVar43.zza(32);
        R = builder43.withProperty(zzbkVar43.zzb()).build();
        FieldDescriptor.Builder builder44 = FieldDescriptor.builder("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzbk zzbkVar44 = new zzbk();
        zzbkVar44.zza(33);
        S = builder44.withProperty(zzbkVar44.zzb()).build();
        FieldDescriptor.Builder builder45 = FieldDescriptor.builder("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzbk zzbkVar45 = new zzbk();
        zzbkVar45.zza(34);
        T = builder45.withProperty(zzbkVar45.zzb()).build();
        FieldDescriptor.Builder builder46 = FieldDescriptor.builder("aggregatedOnDeviceObjectInferenceLogEvent");
        zzbk zzbkVar46 = new zzbk();
        zzbkVar46.zza(35);
        U = builder46.withProperty(zzbkVar46.zzb()).build();
        FieldDescriptor.Builder builder47 = FieldDescriptor.builder("aggregatedOnDeviceTextDetectionLogEvent");
        zzbk zzbkVar47 = new zzbk();
        zzbkVar47.zza(36);
        V = builder47.withProperty(zzbkVar47.zzb()).build();
        FieldDescriptor.Builder builder48 = FieldDescriptor.builder("aggregatedOnDevicePoseDetectionLogEvent");
        zzbk zzbkVar48 = new zzbk();
        zzbkVar48.zza(46);
        W = builder48.withProperty(zzbkVar48.zzb()).build();
        FieldDescriptor.Builder builder49 = FieldDescriptor.builder("aggregatedOnDeviceSegmentationLogEvent");
        zzbk zzbkVar49 = new zzbk();
        zzbkVar49.zza(47);
        X = builder49.withProperty(zzbkVar49.zzb()).build();
        FieldDescriptor.Builder builder50 = FieldDescriptor.builder("pipelineAccelerationInferenceEvents");
        zzbk zzbkVar50 = new zzbk();
        zzbkVar50.zza(69);
        Y = builder50.withProperty(zzbkVar50.zzb()).build();
        FieldDescriptor.Builder builder51 = FieldDescriptor.builder("remoteConfigLogEvent");
        zzbk zzbkVar51 = new zzbk();
        zzbkVar51.zza(42);
        Z = builder51.withProperty(zzbkVar51.zzb()).build();
        FieldDescriptor.Builder builder52 = FieldDescriptor.builder("inputImageConstructionLogEvent");
        zzbk zzbkVar52 = new zzbk();
        zzbkVar52.zza(50);
        a0 = builder52.withProperty(zzbkVar52.zzb()).build();
        FieldDescriptor.Builder builder53 = FieldDescriptor.builder("leakedHandleEvent");
        zzbk zzbkVar53 = new zzbk();
        zzbkVar53.zza(51);
        b0 = builder53.withProperty(zzbkVar53.zzb()).build();
        FieldDescriptor.Builder builder54 = FieldDescriptor.builder("cameraSourceLogEvent");
        zzbk zzbkVar54 = new zzbk();
        zzbkVar54.zza(52);
        c0 = builder54.withProperty(zzbkVar54.zzb()).build();
        FieldDescriptor.Builder builder55 = FieldDescriptor.builder("imageLabelOptionalModuleLogEvent");
        zzbk zzbkVar55 = new zzbk();
        zzbkVar55.zza(53);
        d0 = builder55.withProperty(zzbkVar55.zzb()).build();
        FieldDescriptor.Builder builder56 = FieldDescriptor.builder("languageIdentificationOptionalModuleLogEvent");
        zzbk zzbkVar56 = new zzbk();
        zzbkVar56.zza(54);
        e0 = builder56.withProperty(zzbkVar56.zzb()).build();
        FieldDescriptor.Builder builder57 = FieldDescriptor.builder("faceDetectionOptionalModuleLogEvent");
        zzbk zzbkVar57 = new zzbk();
        zzbkVar57.zza(60);
        f0 = builder57.withProperty(zzbkVar57.zzb()).build();
        FieldDescriptor.Builder builder58 = FieldDescriptor.builder("documentDetectionOptionalModuleLogEvent");
        zzbk zzbkVar58 = new zzbk();
        zzbkVar58.zza(85);
        g0 = builder58.withProperty(zzbkVar58.zzb()).build();
        FieldDescriptor.Builder builder59 = FieldDescriptor.builder("documentCroppingOptionalModuleLogEvent");
        zzbk zzbkVar59 = new zzbk();
        zzbkVar59.zza(86);
        h0 = builder59.withProperty(zzbkVar59.zzb()).build();
        FieldDescriptor.Builder builder60 = FieldDescriptor.builder("documentEnhancementOptionalModuleLogEvent");
        zzbk zzbkVar60 = new zzbk();
        zzbkVar60.zza(87);
        i0 = builder60.withProperty(zzbkVar60.zzb()).build();
        FieldDescriptor.Builder builder61 = FieldDescriptor.builder("nlClassifierOptionalModuleLogEvent");
        zzbk zzbkVar61 = new zzbk();
        zzbkVar61.zza(55);
        j0 = builder61.withProperty(zzbkVar61.zzb()).build();
        FieldDescriptor.Builder builder62 = FieldDescriptor.builder("nlClassifierClientLibraryLogEvent");
        zzbk zzbkVar62 = new zzbk();
        zzbkVar62.zza(56);
        k0 = builder62.withProperty(zzbkVar62.zzb()).build();
        FieldDescriptor.Builder builder63 = FieldDescriptor.builder("accelerationAllowlistLogEvent");
        zzbk zzbkVar63 = new zzbk();
        zzbkVar63.zza(57);
        l0 = builder63.withProperty(zzbkVar63.zzb()).build();
        FieldDescriptor.Builder builder64 = FieldDescriptor.builder("toxicityDetectionCreateEvent");
        zzbk zzbkVar64 = new zzbk();
        zzbkVar64.zza(62);
        m0 = builder64.withProperty(zzbkVar64.zzb()).build();
        FieldDescriptor.Builder builder65 = FieldDescriptor.builder("toxicityDetectionLoadEvent");
        zzbk zzbkVar65 = new zzbk();
        zzbkVar65.zza(63);
        n0 = builder65.withProperty(zzbkVar65.zzb()).build();
        FieldDescriptor.Builder builder66 = FieldDescriptor.builder("toxicityDetectionInferenceEvent");
        zzbk zzbkVar66 = new zzbk();
        zzbkVar66.zza(64);
        o0 = builder66.withProperty(zzbkVar66.zzb()).build();
        FieldDescriptor.Builder builder67 = FieldDescriptor.builder("barcodeDetectionOptionalModuleLogEvent");
        zzbk zzbkVar67 = new zzbk();
        zzbkVar67.zza(65);
        p0 = builder67.withProperty(zzbkVar67.zzb()).build();
        FieldDescriptor.Builder builder68 = FieldDescriptor.builder("customImageLabelOptionalModuleLogEvent");
        zzbk zzbkVar68 = new zzbk();
        zzbkVar68.zza(66);
        q0 = builder68.withProperty(zzbkVar68.zzb()).build();
        FieldDescriptor.Builder builder69 = FieldDescriptor.builder("codeScannerScanApiEvent");
        zzbk zzbkVar69 = new zzbk();
        zzbkVar69.zza(67);
        r0 = builder69.withProperty(zzbkVar69.zzb()).build();
        FieldDescriptor.Builder builder70 = FieldDescriptor.builder("codeScannerOptionalModuleEvent");
        zzbk zzbkVar70 = new zzbk();
        zzbkVar70.zza(68);
        s0 = builder70.withProperty(zzbkVar70.zzb()).build();
        FieldDescriptor.Builder builder71 = FieldDescriptor.builder("onDeviceExplicitContentCreateLogEvent");
        zzbk zzbkVar71 = new zzbk();
        zzbkVar71.zza(70);
        t0 = builder71.withProperty(zzbkVar71.zzb()).build();
        FieldDescriptor.Builder builder72 = FieldDescriptor.builder("onDeviceExplicitContentLoadLogEvent");
        zzbk zzbkVar72 = new zzbk();
        zzbkVar72.zza(71);
        u0 = builder72.withProperty(zzbkVar72.zzb()).build();
        FieldDescriptor.Builder builder73 = FieldDescriptor.builder("onDeviceExplicitContentInferenceLogEvent");
        zzbk zzbkVar73 = new zzbk();
        zzbkVar73.zza(72);
        v0 = builder73.withProperty(zzbkVar73.zzb()).build();
        FieldDescriptor.Builder builder74 = FieldDescriptor.builder("aggregatedOnDeviceExplicitContentLogEvent");
        zzbk zzbkVar74 = new zzbk();
        zzbkVar74.zza(73);
        w0 = builder74.withProperty(zzbkVar74.zzb()).build();
        FieldDescriptor.Builder builder75 = FieldDescriptor.builder("onDeviceFaceMeshCreateLogEvent");
        zzbk zzbkVar75 = new zzbk();
        zzbkVar75.zza(74);
        x0 = builder75.withProperty(zzbkVar75.zzb()).build();
        FieldDescriptor.Builder builder76 = FieldDescriptor.builder("onDeviceFaceMeshLoadLogEvent");
        zzbk zzbkVar76 = new zzbk();
        zzbkVar76.zza(75);
        y0 = builder76.withProperty(zzbkVar76.zzb()).build();
        FieldDescriptor.Builder builder77 = FieldDescriptor.builder("onDeviceFaceMeshLogEvent");
        zzbk zzbkVar77 = new zzbk();
        zzbkVar77.zza(76);
        z0 = builder77.withProperty(zzbkVar77.zzb()).build();
        FieldDescriptor.Builder builder78 = FieldDescriptor.builder("aggregatedOnDeviceFaceMeshLogEvent");
        zzbk zzbkVar78 = new zzbk();
        zzbkVar78.zza(77);
        A0 = builder78.withProperty(zzbkVar78.zzb()).build();
        FieldDescriptor.Builder builder79 = FieldDescriptor.builder("smartReplyOptionalModuleLogEvent");
        zzbk zzbkVar79 = new zzbk();
        zzbkVar79.zza(78);
        B0 = builder79.withProperty(zzbkVar79.zzb()).build();
        FieldDescriptor.Builder builder80 = FieldDescriptor.builder("textDetectionOptionalModuleLogEvent");
        zzbk zzbkVar80 = new zzbk();
        zzbkVar80.zza(80);
        C0 = builder80.withProperty(zzbkVar80.zzb()).build();
        FieldDescriptor.Builder builder81 = FieldDescriptor.builder("onDeviceImageQualityAnalysisCreateLogEvent");
        zzbk zzbkVar81 = new zzbk();
        zzbkVar81.zza(81);
        D0 = builder81.withProperty(zzbkVar81.zzb()).build();
        FieldDescriptor.Builder builder82 = FieldDescriptor.builder("onDeviceImageQualityAnalysisLoadLogEvent");
        zzbk zzbkVar82 = new zzbk();
        zzbkVar82.zza(82);
        E0 = builder82.withProperty(zzbkVar82.zzb()).build();
        FieldDescriptor.Builder builder83 = FieldDescriptor.builder("onDeviceImageQualityAnalysisLogEvent");
        zzbk zzbkVar83 = new zzbk();
        zzbkVar83.zza(83);
        F0 = builder83.withProperty(zzbkVar83.zzb()).build();
        FieldDescriptor.Builder builder84 = FieldDescriptor.builder("aggregatedOnDeviceImageQualityAnalysisLogEvent");
        zzbk zzbkVar84 = new zzbk();
        zzbkVar84.zza(84);
        G0 = builder84.withProperty(zzbkVar84.zzb()).build();
        FieldDescriptor.Builder builder85 = FieldDescriptor.builder("imageQualityAnalysisOptionalModuleLogEvent");
        zzbk zzbkVar85 = new zzbk();
        zzbkVar85.zza(88);
        H0 = builder85.withProperty(zzbkVar85.zzb()).build();
        FieldDescriptor.Builder builder86 = FieldDescriptor.builder("imageCaptioningOptionalModuleLogEvent");
        zzbk zzbkVar86 = new zzbk();
        zzbkVar86.zza(89);
        I0 = builder86.withProperty(zzbkVar86.zzb()).build();
        FieldDescriptor.Builder builder87 = FieldDescriptor.builder("onDeviceImageCaptioningCreateLogEvent");
        zzbk zzbkVar87 = new zzbk();
        zzbkVar87.zza(90);
        J0 = builder87.withProperty(zzbkVar87.zzb()).build();
        FieldDescriptor.Builder builder88 = FieldDescriptor.builder("onDeviceImageCaptioningLoadLogEvent");
        zzbk zzbkVar88 = new zzbk();
        zzbkVar88.zza(91);
        K0 = builder88.withProperty(zzbkVar88.zzb()).build();
        FieldDescriptor.Builder builder89 = FieldDescriptor.builder("onDeviceImageCaptioningInferenceLogEvent");
        zzbk zzbkVar89 = new zzbk();
        zzbkVar89.zza(92);
        L0 = builder89.withProperty(zzbkVar89.zzb()).build();
        FieldDescriptor.Builder builder90 = FieldDescriptor.builder("aggregatedOnDeviceImageCaptioningInferenceLogEvent");
        zzbk zzbkVar90 = new zzbk();
        zzbkVar90.zza(93);
        M0 = builder90.withProperty(zzbkVar90.zzb()).build();
        FieldDescriptor.Builder builder91 = FieldDescriptor.builder("onDeviceDocumentDetectionCreateLogEvent");
        zzbk zzbkVar91 = new zzbk();
        zzbkVar91.zza(94);
        N0 = builder91.withProperty(zzbkVar91.zzb()).build();
        FieldDescriptor.Builder builder92 = FieldDescriptor.builder("onDeviceDocumentDetectionLoadLogEvent");
        zzbk zzbkVar92 = new zzbk();
        zzbkVar92.zza(95);
        O0 = builder92.withProperty(zzbkVar92.zzb()).build();
        FieldDescriptor.Builder builder93 = FieldDescriptor.builder("onDeviceDocumentDetectionLogEvent");
        zzbk zzbkVar93 = new zzbk();
        zzbkVar93.zza(96);
        P0 = builder93.withProperty(zzbkVar93.zzb()).build();
        FieldDescriptor.Builder builder94 = FieldDescriptor.builder("aggregatedOnDeviceDocumentDetectionLogEvent");
        zzbk zzbkVar94 = new zzbk();
        zzbkVar94.zza(97);
        Q0 = builder94.withProperty(zzbkVar94.zzb()).build();
        FieldDescriptor.Builder builder95 = FieldDescriptor.builder("onDeviceDocumentCroppingCreateLogEvent");
        zzbk zzbkVar95 = new zzbk();
        zzbkVar95.zza(98);
        R0 = builder95.withProperty(zzbkVar95.zzb()).build();
        FieldDescriptor.Builder builder96 = FieldDescriptor.builder("onDeviceDocumentCroppingLoadLogEvent");
        zzbk zzbkVar96 = new zzbk();
        zzbkVar96.zza(99);
        S0 = builder96.withProperty(zzbkVar96.zzb()).build();
        FieldDescriptor.Builder builder97 = FieldDescriptor.builder("onDeviceDocumentCroppingLogEvent");
        zzbk zzbkVar97 = new zzbk();
        zzbkVar97.zza(100);
        T0 = builder97.withProperty(zzbkVar97.zzb()).build();
        FieldDescriptor.Builder builder98 = FieldDescriptor.builder("aggregatedOnDeviceDocumentCroppingLogEvent");
        zzbk zzbkVar98 = new zzbk();
        zzbkVar98.zza(101);
        U0 = builder98.withProperty(zzbkVar98.zzb()).build();
        FieldDescriptor.Builder builder99 = FieldDescriptor.builder("onDeviceDocumentEnhancementCreateLogEvent");
        zzbk zzbkVar99 = new zzbk();
        zzbkVar99.zza(102);
        V0 = builder99.withProperty(zzbkVar99.zzb()).build();
        FieldDescriptor.Builder builder100 = FieldDescriptor.builder("onDeviceDocumentEnhancementLoadLogEvent");
        zzbk zzbkVar100 = new zzbk();
        zzbkVar100.zza(103);
        W0 = builder100.withProperty(zzbkVar100.zzb()).build();
        FieldDescriptor.Builder builder101 = FieldDescriptor.builder("onDeviceDocumentEnhancementLogEvent");
        zzbk zzbkVar101 = new zzbk();
        zzbkVar101.zza(104);
        X0 = builder101.withProperty(zzbkVar101.zzb()).build();
        FieldDescriptor.Builder builder102 = FieldDescriptor.builder("aggregatedOnDeviceDocumentEnhancementLogEvent");
        zzbk zzbkVar102 = new zzbk();
        zzbkVar102.zza(105);
        Y0 = builder102.withProperty(zzbkVar102.zzb()).build();
        FieldDescriptor.Builder builder103 = FieldDescriptor.builder("scannerAutoZoomEvent");
        zzbk zzbkVar103 = new zzbk();
        zzbkVar103.zza(106);
        Z0 = builder103.withProperty(zzbkVar103.zzb()).build();
        FieldDescriptor.Builder builder104 = FieldDescriptor.builder("lowLightAutoExposureComputationEvent");
        zzbk zzbkVar104 = new zzbk();
        zzbkVar104.zza(107);
        a1 = builder104.withProperty(zzbkVar104.zzb()).build();
        FieldDescriptor.Builder builder105 = FieldDescriptor.builder("lowLightFrameProcessEvent");
        zzbk zzbkVar105 = new zzbk();
        zzbkVar105.zza(108);
        b1 = builder105.withProperty(zzbkVar105.zzb()).build();
        FieldDescriptor.Builder builder106 = FieldDescriptor.builder("lowLightSceneDetectionEvent");
        zzbk zzbkVar106 = new zzbk();
        zzbkVar106.zza(109);
        c1 = builder106.withProperty(zzbkVar106.zzb()).build();
    }

    @Override // com.google.firebase.encoders.ObjectEncoder
    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) throws IOException {
        zzlq zzlqVar = (zzlq) obj;
        ObjectEncoderContext objectEncoderContext = (ObjectEncoderContext) obj2;
        objectEncoderContext.add(b, zzlqVar.zzf());
        objectEncoderContext.add(c, zzlqVar.zzd());
        objectEncoderContext.add(d, (Object) null);
        objectEncoderContext.add(e, (Object) null);
        objectEncoderContext.add(f, zzlqVar.zze());
        objectEncoderContext.add(g, (Object) null);
        objectEncoderContext.add(h, (Object) null);
        objectEncoderContext.add(i, (Object) null);
        objectEncoderContext.add(j, (Object) null);
        objectEncoderContext.add(k, (Object) null);
        objectEncoderContext.add(l, (Object) null);
        objectEncoderContext.add(m, (Object) null);
        objectEncoderContext.add(n, (Object) null);
        objectEncoderContext.add(o, (Object) null);
        objectEncoderContext.add(p, (Object) null);
        objectEncoderContext.add(q, (Object) null);
        objectEncoderContext.add(r, (Object) null);
        objectEncoderContext.add(s, (Object) null);
        objectEncoderContext.add(t, (Object) null);
        objectEncoderContext.add(u, (Object) null);
        objectEncoderContext.add(v, (Object) null);
        objectEncoderContext.add(w, (Object) null);
        objectEncoderContext.add(x, (Object) null);
        objectEncoderContext.add(y, (Object) null);
        objectEncoderContext.add(z, (Object) null);
        objectEncoderContext.add(A, (Object) null);
        objectEncoderContext.add(B, (Object) null);
        objectEncoderContext.add(C, (Object) null);
        objectEncoderContext.add(D, (Object) null);
        objectEncoderContext.add(E, (Object) null);
        objectEncoderContext.add(F, (Object) null);
        objectEncoderContext.add(G, (Object) null);
        objectEncoderContext.add(H, (Object) null);
        objectEncoderContext.add(I, (Object) null);
        objectEncoderContext.add(J, (Object) null);
        objectEncoderContext.add(K, (Object) null);
        objectEncoderContext.add(L, (Object) null);
        objectEncoderContext.add(M, (Object) null);
        objectEncoderContext.add(N, zzlqVar.zzb());
        objectEncoderContext.add(O, zzlqVar.zza());
        objectEncoderContext.add(P, (Object) null);
        objectEncoderContext.add(Q, (Object) null);
        objectEncoderContext.add(R, (Object) null);
        objectEncoderContext.add(S, (Object) null);
        objectEncoderContext.add(T, (Object) null);
        objectEncoderContext.add(U, (Object) null);
        objectEncoderContext.add(V, (Object) null);
        objectEncoderContext.add(W, (Object) null);
        objectEncoderContext.add(X, (Object) null);
        objectEncoderContext.add(Y, (Object) null);
        objectEncoderContext.add(Z, (Object) null);
        objectEncoderContext.add(a0, (Object) null);
        objectEncoderContext.add(b0, zzlqVar.zzc());
        objectEncoderContext.add(c0, (Object) null);
        objectEncoderContext.add(d0, (Object) null);
        objectEncoderContext.add(e0, (Object) null);
        objectEncoderContext.add(f0, (Object) null);
        objectEncoderContext.add(g0, (Object) null);
        objectEncoderContext.add(h0, (Object) null);
        objectEncoderContext.add(i0, (Object) null);
        objectEncoderContext.add(j0, (Object) null);
        objectEncoderContext.add(k0, (Object) null);
        objectEncoderContext.add(l0, (Object) null);
        objectEncoderContext.add(m0, (Object) null);
        objectEncoderContext.add(n0, (Object) null);
        objectEncoderContext.add(o0, (Object) null);
        objectEncoderContext.add(p0, (Object) null);
        objectEncoderContext.add(q0, (Object) null);
        objectEncoderContext.add(r0, (Object) null);
        objectEncoderContext.add(s0, (Object) null);
        objectEncoderContext.add(t0, (Object) null);
        objectEncoderContext.add(u0, (Object) null);
        objectEncoderContext.add(v0, (Object) null);
        objectEncoderContext.add(w0, (Object) null);
        objectEncoderContext.add(x0, (Object) null);
        objectEncoderContext.add(y0, (Object) null);
        objectEncoderContext.add(z0, (Object) null);
        objectEncoderContext.add(A0, (Object) null);
        objectEncoderContext.add(B0, (Object) null);
        objectEncoderContext.add(C0, (Object) null);
        objectEncoderContext.add(D0, (Object) null);
        objectEncoderContext.add(E0, (Object) null);
        objectEncoderContext.add(F0, (Object) null);
        objectEncoderContext.add(G0, (Object) null);
        objectEncoderContext.add(H0, (Object) null);
        objectEncoderContext.add(I0, (Object) null);
        objectEncoderContext.add(J0, (Object) null);
        objectEncoderContext.add(K0, (Object) null);
        objectEncoderContext.add(L0, (Object) null);
        objectEncoderContext.add(M0, (Object) null);
        objectEncoderContext.add(N0, (Object) null);
        objectEncoderContext.add(O0, (Object) null);
        objectEncoderContext.add(P0, (Object) null);
        objectEncoderContext.add(Q0, (Object) null);
        objectEncoderContext.add(R0, (Object) null);
        objectEncoderContext.add(S0, (Object) null);
        objectEncoderContext.add(T0, (Object) null);
        objectEncoderContext.add(U0, (Object) null);
        objectEncoderContext.add(V0, (Object) null);
        objectEncoderContext.add(W0, (Object) null);
        objectEncoderContext.add(X0, (Object) null);
        objectEncoderContext.add(Y0, (Object) null);
        objectEncoderContext.add(Z0, (Object) null);
        objectEncoderContext.add(a1, (Object) null);
        objectEncoderContext.add(b1, (Object) null);
        objectEncoderContext.add(c1, (Object) null);
    }
}
