package org.bouncycastle.asn1.nist;

import com.jstyle.blesdk1860.constant.BleConst;
import org.bouncycastle.asn1.ASN1ObjectIdentifier;
/* loaded from: classes12.dex */
public interface NISTObjectIdentifiers {
    public static final ASN1ObjectIdentifier aes;
    public static final ASN1ObjectIdentifier dsa_with_sha224;
    public static final ASN1ObjectIdentifier dsa_with_sha256;
    public static final ASN1ObjectIdentifier dsa_with_sha384;
    public static final ASN1ObjectIdentifier dsa_with_sha512;
    public static final ASN1ObjectIdentifier hashAlgs;
    public static final ASN1ObjectIdentifier id_aes128_CBC;
    public static final ASN1ObjectIdentifier id_aes128_CCM;
    public static final ASN1ObjectIdentifier id_aes128_CFB;
    public static final ASN1ObjectIdentifier id_aes128_ECB;
    public static final ASN1ObjectIdentifier id_aes128_GCM;
    public static final ASN1ObjectIdentifier id_aes128_OFB;
    public static final ASN1ObjectIdentifier id_aes128_wrap;
    public static final ASN1ObjectIdentifier id_aes128_wrap_pad;
    public static final ASN1ObjectIdentifier id_aes192_CBC;
    public static final ASN1ObjectIdentifier id_aes192_CCM;
    public static final ASN1ObjectIdentifier id_aes192_CFB;
    public static final ASN1ObjectIdentifier id_aes192_ECB;
    public static final ASN1ObjectIdentifier id_aes192_GCM;
    public static final ASN1ObjectIdentifier id_aes192_OFB;
    public static final ASN1ObjectIdentifier id_aes192_wrap;
    public static final ASN1ObjectIdentifier id_aes192_wrap_pad;
    public static final ASN1ObjectIdentifier id_aes256_CBC;
    public static final ASN1ObjectIdentifier id_aes256_CCM;
    public static final ASN1ObjectIdentifier id_aes256_CFB;
    public static final ASN1ObjectIdentifier id_aes256_ECB;
    public static final ASN1ObjectIdentifier id_aes256_GCM;
    public static final ASN1ObjectIdentifier id_aes256_OFB;
    public static final ASN1ObjectIdentifier id_aes256_wrap;
    public static final ASN1ObjectIdentifier id_aes256_wrap_pad;
    public static final ASN1ObjectIdentifier id_dsa_with_sha2;
    public static final ASN1ObjectIdentifier id_dsa_with_sha3_224;
    public static final ASN1ObjectIdentifier id_dsa_with_sha3_256;
    public static final ASN1ObjectIdentifier id_dsa_with_sha3_384;
    public static final ASN1ObjectIdentifier id_dsa_with_sha3_512;
    public static final ASN1ObjectIdentifier id_ecdsa_with_sha3_224;
    public static final ASN1ObjectIdentifier id_ecdsa_with_sha3_256;
    public static final ASN1ObjectIdentifier id_ecdsa_with_sha3_384;
    public static final ASN1ObjectIdentifier id_ecdsa_with_sha3_512;
    public static final ASN1ObjectIdentifier id_hmacWithSHA3_224;
    public static final ASN1ObjectIdentifier id_hmacWithSHA3_256;
    public static final ASN1ObjectIdentifier id_hmacWithSHA3_384;
    public static final ASN1ObjectIdentifier id_hmacWithSHA3_512;
    public static final ASN1ObjectIdentifier id_rsassa_pkcs1_v1_5_with_sha3_224;
    public static final ASN1ObjectIdentifier id_rsassa_pkcs1_v1_5_with_sha3_256;
    public static final ASN1ObjectIdentifier id_rsassa_pkcs1_v1_5_with_sha3_384;
    public static final ASN1ObjectIdentifier id_rsassa_pkcs1_v1_5_with_sha3_512;
    public static final ASN1ObjectIdentifier id_sha224;
    public static final ASN1ObjectIdentifier id_sha256;
    public static final ASN1ObjectIdentifier id_sha384;
    public static final ASN1ObjectIdentifier id_sha3_224;
    public static final ASN1ObjectIdentifier id_sha3_256;
    public static final ASN1ObjectIdentifier id_sha3_384;
    public static final ASN1ObjectIdentifier id_sha3_512;
    public static final ASN1ObjectIdentifier id_sha512;
    public static final ASN1ObjectIdentifier id_sha512_224;
    public static final ASN1ObjectIdentifier id_sha512_256;
    public static final ASN1ObjectIdentifier id_shake128;
    public static final ASN1ObjectIdentifier id_shake256;
    public static final ASN1ObjectIdentifier nistAlgorithm;
    public static final ASN1ObjectIdentifier sigAlgs;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("2.16.840.1.101.3.4");
        nistAlgorithm = aSN1ObjectIdentifier;
        ASN1ObjectIdentifier branch = aSN1ObjectIdentifier.branch("2");
        hashAlgs = branch;
        id_sha256 = branch.branch("1");
        id_sha384 = branch.branch("2");
        id_sha512 = branch.branch("3");
        id_sha224 = branch.branch(BleConst.GetDeviceInfo);
        id_sha512_224 = branch.branch(BleConst.SetDeviceInfo);
        id_sha512_256 = branch.branch(BleConst.CMD_Set_Mac);
        id_sha3_224 = branch.branch(BleConst.GetStepGoal);
        id_sha3_256 = branch.branch(BleConst.SetStepGoal);
        id_sha3_384 = branch.branch(BleConst.GetDeviceBatteryLevel);
        id_sha3_512 = branch.branch(BleConst.GetDeviceMacAddress);
        id_shake128 = branch.branch(BleConst.GetDeviceVersion);
        id_shake256 = branch.branch(BleConst.CMD_Reset);
        id_hmacWithSHA3_224 = branch.branch(BleConst.CMD_MCUReset);
        id_hmacWithSHA3_256 = branch.branch(BleConst.SetMotorVibrationWithTimes);
        id_hmacWithSHA3_384 = branch.branch(BleConst.GetDeviceName);
        id_hmacWithSHA3_512 = branch.branch(BleConst.SetDeviceName);
        ASN1ObjectIdentifier branch2 = aSN1ObjectIdentifier.branch("1");
        aes = branch2;
        id_aes128_ECB = branch2.branch("1");
        id_aes128_CBC = branch2.branch("2");
        id_aes128_OFB = branch2.branch("3");
        id_aes128_CFB = branch2.branch(BleConst.GetDeviceInfo);
        id_aes128_wrap = branch2.branch(BleConst.SetDeviceInfo);
        id_aes128_GCM = branch2.branch(BleConst.CMD_Set_Mac);
        id_aes128_CCM = branch2.branch(BleConst.GetStepGoal);
        id_aes128_wrap_pad = branch2.branch(BleConst.SetStepGoal);
        id_aes192_ECB = branch2.branch(BleConst.GetSedentaryReminder);
        id_aes192_CBC = branch2.branch(BleConst.SetSedentaryReminder);
        id_aes192_OFB = branch2.branch(BleConst.RealTimeStep);
        id_aes192_CFB = branch2.branch(BleConst.GetTotalActivityData);
        id_aes192_wrap = branch2.branch(BleConst.GetDetailActivityData);
        id_aes192_GCM = branch2.branch(BleConst.GetDetailSleepData);
        id_aes192_CCM = branch2.branch(BleConst.GetDynamicHR);
        id_aes192_wrap_pad = branch2.branch(BleConst.GetStaticHR);
        id_aes256_ECB = branch2.branch(BleConst.Gps);
        id_aes256_CBC = branch2.branch("42");
        id_aes256_OFB = branch2.branch(BleConst.CMD_Set_TemperatureCorrection);
        id_aes256_CFB = branch2.branch(BleConst.Weather);
        id_aes256_wrap = branch2.branch(BleConst.Braceletdial);
        id_aes256_GCM = branch2.branch(BleConst.Braceletdialok);
        id_aes256_CCM = branch2.branch(BleConst.SportMode);
        id_aes256_wrap_pad = branch2.branch(BleConst.GetSportMode);
        ASN1ObjectIdentifier branch3 = aSN1ObjectIdentifier.branch("3");
        sigAlgs = branch3;
        id_dsa_with_sha2 = branch3;
        dsa_with_sha224 = branch3.branch("1");
        dsa_with_sha256 = branch3.branch("2");
        dsa_with_sha384 = branch3.branch("3");
        dsa_with_sha512 = branch3.branch(BleConst.GetDeviceInfo);
        id_dsa_with_sha3_224 = branch3.branch(BleConst.SetDeviceInfo);
        id_dsa_with_sha3_256 = branch3.branch(BleConst.CMD_Set_Mac);
        id_dsa_with_sha3_384 = branch3.branch(BleConst.GetStepGoal);
        id_dsa_with_sha3_512 = branch3.branch(BleConst.SetStepGoal);
        id_ecdsa_with_sha3_224 = branch3.branch(BleConst.GetDeviceBatteryLevel);
        id_ecdsa_with_sha3_256 = branch3.branch(BleConst.GetDeviceMacAddress);
        id_ecdsa_with_sha3_384 = branch3.branch(BleConst.GetDeviceVersion);
        id_ecdsa_with_sha3_512 = branch3.branch(BleConst.CMD_Reset);
        id_rsassa_pkcs1_v1_5_with_sha3_224 = branch3.branch(BleConst.CMD_MCUReset);
        id_rsassa_pkcs1_v1_5_with_sha3_256 = branch3.branch(BleConst.SetMotorVibrationWithTimes);
        id_rsassa_pkcs1_v1_5_with_sha3_384 = branch3.branch(BleConst.GetDeviceName);
        id_rsassa_pkcs1_v1_5_with_sha3_512 = branch3.branch(BleConst.SetDeviceName);
    }
}
