package com.coveiot.android.leonardo.firebaseservices.enums;
/* loaded from: classes2.dex */
public enum InboxMessageTypes {
    PANIC_ALERT_MESSAGE,
    GENERIC_MESSAGE,
    NOMINEE_ACCEPT_REJECT_MESSAGE,
    YOU_WERE_NOMINATED_MESSAGE,
    YOU_WERE_INVITED_MESSAGE,
    INVITEE_ACCEPT_REJECT_MESSAGE,
    FITNESS_ACCEPT_REJECT_MESSAGE,
    FITNESSBUDDY_CHEER_MESSAGE,
    THINKING_ABOUT_YOU,
    SMILE_BACK,
    REL_GUARDIAN_UNAVAILABLE_MESSAGE,
    FIRMWARE_UPDATE,
    APP_UPDATE,
    FITNESS_REPORT_SUBSCRIPTION,
    WORKOUT_VIDEOS_UPDATE
}
