package com.google.android.gms.internal.mlkit_vision_barcode;

import com.google.firebase.encoders.FieldDescriptor;
import com.google.firebase.encoders.ObjectEncoder;
import com.google.firebase.encoders.ObjectEncoderContext;
import java.io.IOException;
/* loaded from: classes9.dex */
public final class n5 implements ObjectEncoder {
    public static final FieldDescriptor A;
    public static final FieldDescriptor A0;
    public static final FieldDescriptor B;
    public static final FieldDescriptor B0;
    public static final FieldDescriptor C;
    public static final FieldDescriptor C0;
    public static final FieldDescriptor D;
    public static final FieldDescriptor D0;
    public static final FieldDescriptor E;
    public static final FieldDescriptor E0;
    public static final FieldDescriptor F;
    public static final FieldDescriptor F0;
    public static final FieldDescriptor G;
    public static final FieldDescriptor G0;
    public static final FieldDescriptor H;
    public static final FieldDescriptor H0;
    public static final FieldDescriptor I;
    public static final FieldDescriptor I0;
    public static final FieldDescriptor J;
    public static final FieldDescriptor J0;
    public static final FieldDescriptor K;
    public static final FieldDescriptor K0;
    public static final FieldDescriptor L;
    public static final FieldDescriptor L0;
    public static final FieldDescriptor M;
    public static final FieldDescriptor M0;
    public static final FieldDescriptor N;
    public static final FieldDescriptor N0;
    public static final FieldDescriptor O;
    public static final FieldDescriptor O0;
    public static final FieldDescriptor P;
    public static final FieldDescriptor P0;
    public static final FieldDescriptor Q;
    public static final FieldDescriptor Q0;
    public static final FieldDescriptor R;
    public static final FieldDescriptor R0;
    public static final FieldDescriptor S;
    public static final FieldDescriptor S0;
    public static final FieldDescriptor T;
    public static final FieldDescriptor T0;
    public static final FieldDescriptor U;
    public static final FieldDescriptor U0;
    public static final FieldDescriptor V;
    public static final FieldDescriptor V0;
    public static final FieldDescriptor W;
    public static final FieldDescriptor W0;
    public static final FieldDescriptor X;
    public static final FieldDescriptor X0;
    public static final FieldDescriptor Y;
    public static final FieldDescriptor Y0;
    public static final FieldDescriptor Z;
    public static final FieldDescriptor Z0;

    /* renamed from: a  reason: collision with root package name */
    public static final n5 f9459a = new n5();
    public static final FieldDescriptor a0;
    public static final FieldDescriptor a1;
    public static final FieldDescriptor b;
    public static final FieldDescriptor b0;
    public static final FieldDescriptor b1;
    public static final FieldDescriptor c;
    public static final FieldDescriptor c0;
    public static final FieldDescriptor c1;
    public static final FieldDescriptor d;
    public static final FieldDescriptor d0;
    public static final FieldDescriptor e;
    public static final FieldDescriptor e0;
    public static final FieldDescriptor f;
    public static final FieldDescriptor f0;
    public static final FieldDescriptor g;
    public static final FieldDescriptor g0;
    public static final FieldDescriptor h;
    public static final FieldDescriptor h0;
    public static final FieldDescriptor i;
    public static final FieldDescriptor i0;
    public static final FieldDescriptor j;
    public static final FieldDescriptor j0;
    public static final FieldDescriptor k;
    public static final FieldDescriptor k0;
    public static final FieldDescriptor l;
    public static final FieldDescriptor l0;
    public static final FieldDescriptor m;
    public static final FieldDescriptor m0;
    public static final FieldDescriptor n;
    public static final FieldDescriptor n0;
    public static final FieldDescriptor o;
    public static final FieldDescriptor o0;
    public static final FieldDescriptor p;
    public static final FieldDescriptor p0;
    public static final FieldDescriptor q;
    public static final FieldDescriptor q0;
    public static final FieldDescriptor r;
    public static final FieldDescriptor r0;
    public static final FieldDescriptor s;
    public static final FieldDescriptor s0;
    public static final FieldDescriptor t;
    public static final FieldDescriptor t0;
    public static final FieldDescriptor u;
    public static final FieldDescriptor u0;
    public static final FieldDescriptor v;
    public static final FieldDescriptor v0;
    public static final FieldDescriptor w;
    public static final FieldDescriptor w0;
    public static final FieldDescriptor x;
    public static final FieldDescriptor x0;
    public static final FieldDescriptor y;
    public static final FieldDescriptor y0;
    public static final FieldDescriptor z;
    public static final FieldDescriptor z0;

    static {
        FieldDescriptor.Builder builder = FieldDescriptor.builder("systemInfo");
        zzfc zzfcVar = new zzfc();
        zzfcVar.zza(1);
        b = builder.withProperty(zzfcVar.zzb()).build();
        FieldDescriptor.Builder builder2 = FieldDescriptor.builder("eventName");
        zzfc zzfcVar2 = new zzfc();
        zzfcVar2.zza(2);
        c = builder2.withProperty(zzfcVar2.zzb()).build();
        FieldDescriptor.Builder builder3 = FieldDescriptor.builder("isThickClient");
        zzfc zzfcVar3 = new zzfc();
        zzfcVar3.zza(37);
        d = builder3.withProperty(zzfcVar3.zzb()).build();
        FieldDescriptor.Builder builder4 = FieldDescriptor.builder("clientType");
        zzfc zzfcVar4 = new zzfc();
        zzfcVar4.zza(61);
        e = builder4.withProperty(zzfcVar4.zzb()).build();
        FieldDescriptor.Builder builder5 = FieldDescriptor.builder("modelDownloadLogEvent");
        zzfc zzfcVar5 = new zzfc();
        zzfcVar5.zza(3);
        f = builder5.withProperty(zzfcVar5.zzb()).build();
        FieldDescriptor.Builder builder6 = FieldDescriptor.builder("customModelLoadLogEvent");
        zzfc zzfcVar6 = new zzfc();
        zzfcVar6.zza(20);
        g = builder6.withProperty(zzfcVar6.zzb()).build();
        FieldDescriptor.Builder builder7 = FieldDescriptor.builder("customModelInferenceLogEvent");
        zzfc zzfcVar7 = new zzfc();
        zzfcVar7.zza(4);
        h = builder7.withProperty(zzfcVar7.zzb()).build();
        FieldDescriptor.Builder builder8 = FieldDescriptor.builder("customModelCreateLogEvent");
        zzfc zzfcVar8 = new zzfc();
        zzfcVar8.zza(29);
        i = builder8.withProperty(zzfcVar8.zzb()).build();
        FieldDescriptor.Builder builder9 = FieldDescriptor.builder("onDeviceFaceDetectionLogEvent");
        zzfc zzfcVar9 = new zzfc();
        zzfcVar9.zza(5);
        j = builder9.withProperty(zzfcVar9.zzb()).build();
        FieldDescriptor.Builder builder10 = FieldDescriptor.builder("onDeviceFaceLoadLogEvent");
        zzfc zzfcVar10 = new zzfc();
        zzfcVar10.zza(59);
        k = builder10.withProperty(zzfcVar10.zzb()).build();
        FieldDescriptor.Builder builder11 = FieldDescriptor.builder("onDeviceTextDetectionLogEvent");
        zzfc zzfcVar11 = new zzfc();
        zzfcVar11.zza(6);
        l = builder11.withProperty(zzfcVar11.zzb()).build();
        FieldDescriptor.Builder builder12 = FieldDescriptor.builder("onDeviceTextDetectionLoadLogEvent");
        zzfc zzfcVar12 = new zzfc();
        zzfcVar12.zza(79);
        m = builder12.withProperty(zzfcVar12.zzb()).build();
        FieldDescriptor.Builder builder13 = FieldDescriptor.builder("onDeviceBarcodeDetectionLogEvent");
        zzfc zzfcVar13 = new zzfc();
        zzfcVar13.zza(7);
        n = builder13.withProperty(zzfcVar13.zzb()).build();
        FieldDescriptor.Builder builder14 = FieldDescriptor.builder("onDeviceBarcodeLoadLogEvent");
        zzfc zzfcVar14 = new zzfc();
        zzfcVar14.zza(58);
        o = builder14.withProperty(zzfcVar14.zzb()).build();
        FieldDescriptor.Builder builder15 = FieldDescriptor.builder("onDeviceImageLabelCreateLogEvent");
        zzfc zzfcVar15 = new zzfc();
        zzfcVar15.zza(48);
        p = builder15.withProperty(zzfcVar15.zzb()).build();
        FieldDescriptor.Builder builder16 = FieldDescriptor.builder("onDeviceImageLabelLoadLogEvent");
        zzfc zzfcVar16 = new zzfc();
        zzfcVar16.zza(49);
        q = builder16.withProperty(zzfcVar16.zzb()).build();
        FieldDescriptor.Builder builder17 = FieldDescriptor.builder("onDeviceImageLabelDetectionLogEvent");
        zzfc zzfcVar17 = new zzfc();
        zzfcVar17.zza(18);
        r = builder17.withProperty(zzfcVar17.zzb()).build();
        FieldDescriptor.Builder builder18 = FieldDescriptor.builder("onDeviceObjectCreateLogEvent");
        zzfc zzfcVar18 = new zzfc();
        zzfcVar18.zza(26);
        s = builder18.withProperty(zzfcVar18.zzb()).build();
        FieldDescriptor.Builder builder19 = FieldDescriptor.builder("onDeviceObjectLoadLogEvent");
        zzfc zzfcVar19 = new zzfc();
        zzfcVar19.zza(27);
        t = builder19.withProperty(zzfcVar19.zzb()).build();
        FieldDescriptor.Builder builder20 = FieldDescriptor.builder("onDeviceObjectInferenceLogEvent");
        zzfc zzfcVar20 = new zzfc();
        zzfcVar20.zza(28);
        u = builder20.withProperty(zzfcVar20.zzb()).build();
        FieldDescriptor.Builder builder21 = FieldDescriptor.builder("onDevicePoseDetectionLogEvent");
        zzfc zzfcVar21 = new zzfc();
        zzfcVar21.zza(44);
        v = builder21.withProperty(zzfcVar21.zzb()).build();
        FieldDescriptor.Builder builder22 = FieldDescriptor.builder("onDeviceSegmentationLogEvent");
        zzfc zzfcVar22 = new zzfc();
        zzfcVar22.zza(45);
        w = builder22.withProperty(zzfcVar22.zzb()).build();
        FieldDescriptor.Builder builder23 = FieldDescriptor.builder("onDeviceSmartReplyLogEvent");
        zzfc zzfcVar23 = new zzfc();
        zzfcVar23.zza(19);
        x = builder23.withProperty(zzfcVar23.zzb()).build();
        FieldDescriptor.Builder builder24 = FieldDescriptor.builder("onDeviceLanguageIdentificationLogEvent");
        zzfc zzfcVar24 = new zzfc();
        zzfcVar24.zza(21);
        y = builder24.withProperty(zzfcVar24.zzb()).build();
        FieldDescriptor.Builder builder25 = FieldDescriptor.builder("onDeviceTranslationLogEvent");
        zzfc zzfcVar25 = new zzfc();
        zzfcVar25.zza(22);
        z = builder25.withProperty(zzfcVar25.zzb()).build();
        FieldDescriptor.Builder builder26 = FieldDescriptor.builder("cloudFaceDetectionLogEvent");
        zzfc zzfcVar26 = new zzfc();
        zzfcVar26.zza(8);
        A = builder26.withProperty(zzfcVar26.zzb()).build();
        FieldDescriptor.Builder builder27 = FieldDescriptor.builder("cloudCropHintDetectionLogEvent");
        zzfc zzfcVar27 = new zzfc();
        zzfcVar27.zza(9);
        B = builder27.withProperty(zzfcVar27.zzb()).build();
        FieldDescriptor.Builder builder28 = FieldDescriptor.builder("cloudDocumentTextDetectionLogEvent");
        zzfc zzfcVar28 = new zzfc();
        zzfcVar28.zza(10);
        C = builder28.withProperty(zzfcVar28.zzb()).build();
        FieldDescriptor.Builder builder29 = FieldDescriptor.builder("cloudImagePropertiesDetectionLogEvent");
        zzfc zzfcVar29 = new zzfc();
        zzfcVar29.zza(11);
        D = builder29.withProperty(zzfcVar29.zzb()).build();
        FieldDescriptor.Builder builder30 = FieldDescriptor.builder("cloudImageLabelDetectionLogEvent");
        zzfc zzfcVar30 = new zzfc();
        zzfcVar30.zza(12);
        E = builder30.withProperty(zzfcVar30.zzb()).build();
        FieldDescriptor.Builder builder31 = FieldDescriptor.builder("cloudLandmarkDetectionLogEvent");
        zzfc zzfcVar31 = new zzfc();
        zzfcVar31.zza(13);
        F = builder31.withProperty(zzfcVar31.zzb()).build();
        FieldDescriptor.Builder builder32 = FieldDescriptor.builder("cloudLogoDetectionLogEvent");
        zzfc zzfcVar32 = new zzfc();
        zzfcVar32.zza(14);
        G = builder32.withProperty(zzfcVar32.zzb()).build();
        FieldDescriptor.Builder builder33 = FieldDescriptor.builder("cloudSafeSearchDetectionLogEvent");
        zzfc zzfcVar33 = new zzfc();
        zzfcVar33.zza(15);
        H = builder33.withProperty(zzfcVar33.zzb()).build();
        FieldDescriptor.Builder builder34 = FieldDescriptor.builder("cloudTextDetectionLogEvent");
        zzfc zzfcVar34 = new zzfc();
        zzfcVar34.zza(16);
        I = builder34.withProperty(zzfcVar34.zzb()).build();
        FieldDescriptor.Builder builder35 = FieldDescriptor.builder("cloudWebSearchDetectionLogEvent");
        zzfc zzfcVar35 = new zzfc();
        zzfcVar35.zza(17);
        J = builder35.withProperty(zzfcVar35.zzb()).build();
        FieldDescriptor.Builder builder36 = FieldDescriptor.builder("automlImageLabelingCreateLogEvent");
        zzfc zzfcVar36 = new zzfc();
        zzfcVar36.zza(23);
        K = builder36.withProperty(zzfcVar36.zzb()).build();
        FieldDescriptor.Builder builder37 = FieldDescriptor.builder("automlImageLabelingLoadLogEvent");
        zzfc zzfcVar37 = new zzfc();
        zzfcVar37.zza(24);
        L = builder37.withProperty(zzfcVar37.zzb()).build();
        FieldDescriptor.Builder builder38 = FieldDescriptor.builder("automlImageLabelingInferenceLogEvent");
        zzfc zzfcVar38 = new zzfc();
        zzfcVar38.zza(25);
        M = builder38.withProperty(zzfcVar38.zzb()).build();
        FieldDescriptor.Builder builder39 = FieldDescriptor.builder("isModelDownloadedLogEvent");
        zzfc zzfcVar39 = new zzfc();
        zzfcVar39.zza(39);
        N = builder39.withProperty(zzfcVar39.zzb()).build();
        FieldDescriptor.Builder builder40 = FieldDescriptor.builder("deleteModelLogEvent");
        zzfc zzfcVar40 = new zzfc();
        zzfcVar40.zza(40);
        O = builder40.withProperty(zzfcVar40.zzb()).build();
        FieldDescriptor.Builder builder41 = FieldDescriptor.builder("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzfc zzfcVar41 = new zzfc();
        zzfcVar41.zza(30);
        P = builder41.withProperty(zzfcVar41.zzb()).build();
        FieldDescriptor.Builder builder42 = FieldDescriptor.builder("aggregatedCustomModelInferenceLogEvent");
        zzfc zzfcVar42 = new zzfc();
        zzfcVar42.zza(31);
        Q = builder42.withProperty(zzfcVar42.zzb()).build();
        FieldDescriptor.Builder builder43 = FieldDescriptor.builder("aggregatedOnDeviceFaceDetectionLogEvent");
        zzfc zzfcVar43 = new zzfc();
        zzfcVar43.zza(32);
        R = builder43.withProperty(zzfcVar43.zzb()).build();
        FieldDescriptor.Builder builder44 = FieldDescriptor.builder("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzfc zzfcVar44 = new zzfc();
        zzfcVar44.zza(33);
        S = builder44.withProperty(zzfcVar44.zzb()).build();
        FieldDescriptor.Builder builder45 = FieldDescriptor.builder("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzfc zzfcVar45 = new zzfc();
        zzfcVar45.zza(34);
        T = builder45.withProperty(zzfcVar45.zzb()).build();
        FieldDescriptor.Builder builder46 = FieldDescriptor.builder("aggregatedOnDeviceObjectInferenceLogEvent");
        zzfc zzfcVar46 = new zzfc();
        zzfcVar46.zza(35);
        U = builder46.withProperty(zzfcVar46.zzb()).build();
        FieldDescriptor.Builder builder47 = FieldDescriptor.builder("aggregatedOnDeviceTextDetectionLogEvent");
        zzfc zzfcVar47 = new zzfc();
        zzfcVar47.zza(36);
        V = builder47.withProperty(zzfcVar47.zzb()).build();
        FieldDescriptor.Builder builder48 = FieldDescriptor.builder("aggregatedOnDevicePoseDetectionLogEvent");
        zzfc zzfcVar48 = new zzfc();
        zzfcVar48.zza(46);
        W = builder48.withProperty(zzfcVar48.zzb()).build();
        FieldDescriptor.Builder builder49 = FieldDescriptor.builder("aggregatedOnDeviceSegmentationLogEvent");
        zzfc zzfcVar49 = new zzfc();
        zzfcVar49.zza(47);
        X = builder49.withProperty(zzfcVar49.zzb()).build();
        FieldDescriptor.Builder builder50 = FieldDescriptor.builder("pipelineAccelerationInferenceEvents");
        zzfc zzfcVar50 = new zzfc();
        zzfcVar50.zza(69);
        Y = builder50.withProperty(zzfcVar50.zzb()).build();
        FieldDescriptor.Builder builder51 = FieldDescriptor.builder("remoteConfigLogEvent");
        zzfc zzfcVar51 = new zzfc();
        zzfcVar51.zza(42);
        Z = builder51.withProperty(zzfcVar51.zzb()).build();
        FieldDescriptor.Builder builder52 = FieldDescriptor.builder("inputImageConstructionLogEvent");
        zzfc zzfcVar52 = new zzfc();
        zzfcVar52.zza(50);
        a0 = builder52.withProperty(zzfcVar52.zzb()).build();
        FieldDescriptor.Builder builder53 = FieldDescriptor.builder("leakedHandleEvent");
        zzfc zzfcVar53 = new zzfc();
        zzfcVar53.zza(51);
        b0 = builder53.withProperty(zzfcVar53.zzb()).build();
        FieldDescriptor.Builder builder54 = FieldDescriptor.builder("cameraSourceLogEvent");
        zzfc zzfcVar54 = new zzfc();
        zzfcVar54.zza(52);
        c0 = builder54.withProperty(zzfcVar54.zzb()).build();
        FieldDescriptor.Builder builder55 = FieldDescriptor.builder("imageLabelOptionalModuleLogEvent");
        zzfc zzfcVar55 = new zzfc();
        zzfcVar55.zza(53);
        d0 = builder55.withProperty(zzfcVar55.zzb()).build();
        FieldDescriptor.Builder builder56 = FieldDescriptor.builder("languageIdentificationOptionalModuleLogEvent");
        zzfc zzfcVar56 = new zzfc();
        zzfcVar56.zza(54);
        e0 = builder56.withProperty(zzfcVar56.zzb()).build();
        FieldDescriptor.Builder builder57 = FieldDescriptor.builder("faceDetectionOptionalModuleLogEvent");
        zzfc zzfcVar57 = new zzfc();
        zzfcVar57.zza(60);
        f0 = builder57.withProperty(zzfcVar57.zzb()).build();
        FieldDescriptor.Builder builder58 = FieldDescriptor.builder("documentDetectionOptionalModuleLogEvent");
        zzfc zzfcVar58 = new zzfc();
        zzfcVar58.zza(85);
        g0 = builder58.withProperty(zzfcVar58.zzb()).build();
        FieldDescriptor.Builder builder59 = FieldDescriptor.builder("documentCroppingOptionalModuleLogEvent");
        zzfc zzfcVar59 = new zzfc();
        zzfcVar59.zza(86);
        h0 = builder59.withProperty(zzfcVar59.zzb()).build();
        FieldDescriptor.Builder builder60 = FieldDescriptor.builder("documentEnhancementOptionalModuleLogEvent");
        zzfc zzfcVar60 = new zzfc();
        zzfcVar60.zza(87);
        i0 = builder60.withProperty(zzfcVar60.zzb()).build();
        FieldDescriptor.Builder builder61 = FieldDescriptor.builder("nlClassifierOptionalModuleLogEvent");
        zzfc zzfcVar61 = new zzfc();
        zzfcVar61.zza(55);
        j0 = builder61.withProperty(zzfcVar61.zzb()).build();
        FieldDescriptor.Builder builder62 = FieldDescriptor.builder("nlClassifierClientLibraryLogEvent");
        zzfc zzfcVar62 = new zzfc();
        zzfcVar62.zza(56);
        k0 = builder62.withProperty(zzfcVar62.zzb()).build();
        FieldDescriptor.Builder builder63 = FieldDescriptor.builder("accelerationAllowlistLogEvent");
        zzfc zzfcVar63 = new zzfc();
        zzfcVar63.zza(57);
        l0 = builder63.withProperty(zzfcVar63.zzb()).build();
        FieldDescriptor.Builder builder64 = FieldDescriptor.builder("toxicityDetectionCreateEvent");
        zzfc zzfcVar64 = new zzfc();
        zzfcVar64.zza(62);
        m0 = builder64.withProperty(zzfcVar64.zzb()).build();
        FieldDescriptor.Builder builder65 = FieldDescriptor.builder("toxicityDetectionLoadEvent");
        zzfc zzfcVar65 = new zzfc();
        zzfcVar65.zza(63);
        n0 = builder65.withProperty(zzfcVar65.zzb()).build();
        FieldDescriptor.Builder builder66 = FieldDescriptor.builder("toxicityDetectionInferenceEvent");
        zzfc zzfcVar66 = new zzfc();
        zzfcVar66.zza(64);
        o0 = builder66.withProperty(zzfcVar66.zzb()).build();
        FieldDescriptor.Builder builder67 = FieldDescriptor.builder("barcodeDetectionOptionalModuleLogEvent");
        zzfc zzfcVar67 = new zzfc();
        zzfcVar67.zza(65);
        p0 = builder67.withProperty(zzfcVar67.zzb()).build();
        FieldDescriptor.Builder builder68 = FieldDescriptor.builder("customImageLabelOptionalModuleLogEvent");
        zzfc zzfcVar68 = new zzfc();
        zzfcVar68.zza(66);
        q0 = builder68.withProperty(zzfcVar68.zzb()).build();
        FieldDescriptor.Builder builder69 = FieldDescriptor.builder("codeScannerScanApiEvent");
        zzfc zzfcVar69 = new zzfc();
        zzfcVar69.zza(67);
        r0 = builder69.withProperty(zzfcVar69.zzb()).build();
        FieldDescriptor.Builder builder70 = FieldDescriptor.builder("codeScannerOptionalModuleEvent");
        zzfc zzfcVar70 = new zzfc();
        zzfcVar70.zza(68);
        s0 = builder70.withProperty(zzfcVar70.zzb()).build();
        FieldDescriptor.Builder builder71 = FieldDescriptor.builder("onDeviceExplicitContentCreateLogEvent");
        zzfc zzfcVar71 = new zzfc();
        zzfcVar71.zza(70);
        t0 = builder71.withProperty(zzfcVar71.zzb()).build();
        FieldDescriptor.Builder builder72 = FieldDescriptor.builder("onDeviceExplicitContentLoadLogEvent");
        zzfc zzfcVar72 = new zzfc();
        zzfcVar72.zza(71);
        u0 = builder72.withProperty(zzfcVar72.zzb()).build();
        FieldDescriptor.Builder builder73 = FieldDescriptor.builder("onDeviceExplicitContentInferenceLogEvent");
        zzfc zzfcVar73 = new zzfc();
        zzfcVar73.zza(72);
        v0 = builder73.withProperty(zzfcVar73.zzb()).build();
        FieldDescriptor.Builder builder74 = FieldDescriptor.builder("aggregatedOnDeviceExplicitContentLogEvent");
        zzfc zzfcVar74 = new zzfc();
        zzfcVar74.zza(73);
        w0 = builder74.withProperty(zzfcVar74.zzb()).build();
        FieldDescriptor.Builder builder75 = FieldDescriptor.builder("onDeviceFaceMeshCreateLogEvent");
        zzfc zzfcVar75 = new zzfc();
        zzfcVar75.zza(74);
        x0 = builder75.withProperty(zzfcVar75.zzb()).build();
        FieldDescriptor.Builder builder76 = FieldDescriptor.builder("onDeviceFaceMeshLoadLogEvent");
        zzfc zzfcVar76 = new zzfc();
        zzfcVar76.zza(75);
        y0 = builder76.withProperty(zzfcVar76.zzb()).build();
        FieldDescriptor.Builder builder77 = FieldDescriptor.builder("onDeviceFaceMeshLogEvent");
        zzfc zzfcVar77 = new zzfc();
        zzfcVar77.zza(76);
        z0 = builder77.withProperty(zzfcVar77.zzb()).build();
        FieldDescriptor.Builder builder78 = FieldDescriptor.builder("aggregatedOnDeviceFaceMeshLogEvent");
        zzfc zzfcVar78 = new zzfc();
        zzfcVar78.zza(77);
        A0 = builder78.withProperty(zzfcVar78.zzb()).build();
        FieldDescriptor.Builder builder79 = FieldDescriptor.builder("smartReplyOptionalModuleLogEvent");
        zzfc zzfcVar79 = new zzfc();
        zzfcVar79.zza(78);
        B0 = builder79.withProperty(zzfcVar79.zzb()).build();
        FieldDescriptor.Builder builder80 = FieldDescriptor.builder("textDetectionOptionalModuleLogEvent");
        zzfc zzfcVar80 = new zzfc();
        zzfcVar80.zza(80);
        C0 = builder80.withProperty(zzfcVar80.zzb()).build();
        FieldDescriptor.Builder builder81 = FieldDescriptor.builder("onDeviceImageQualityAnalysisCreateLogEvent");
        zzfc zzfcVar81 = new zzfc();
        zzfcVar81.zza(81);
        D0 = builder81.withProperty(zzfcVar81.zzb()).build();
        FieldDescriptor.Builder builder82 = FieldDescriptor.builder("onDeviceImageQualityAnalysisLoadLogEvent");
        zzfc zzfcVar82 = new zzfc();
        zzfcVar82.zza(82);
        E0 = builder82.withProperty(zzfcVar82.zzb()).build();
        FieldDescriptor.Builder builder83 = FieldDescriptor.builder("onDeviceImageQualityAnalysisLogEvent");
        zzfc zzfcVar83 = new zzfc();
        zzfcVar83.zza(83);
        F0 = builder83.withProperty(zzfcVar83.zzb()).build();
        FieldDescriptor.Builder builder84 = FieldDescriptor.builder("aggregatedOnDeviceImageQualityAnalysisLogEvent");
        zzfc zzfcVar84 = new zzfc();
        zzfcVar84.zza(84);
        G0 = builder84.withProperty(zzfcVar84.zzb()).build();
        FieldDescriptor.Builder builder85 = FieldDescriptor.builder("imageQualityAnalysisOptionalModuleLogEvent");
        zzfc zzfcVar85 = new zzfc();
        zzfcVar85.zza(88);
        H0 = builder85.withProperty(zzfcVar85.zzb()).build();
        FieldDescriptor.Builder builder86 = FieldDescriptor.builder("imageCaptioningOptionalModuleLogEvent");
        zzfc zzfcVar86 = new zzfc();
        zzfcVar86.zza(89);
        I0 = builder86.withProperty(zzfcVar86.zzb()).build();
        FieldDescriptor.Builder builder87 = FieldDescriptor.builder("onDeviceImageCaptioningCreateLogEvent");
        zzfc zzfcVar87 = new zzfc();
        zzfcVar87.zza(90);
        J0 = builder87.withProperty(zzfcVar87.zzb()).build();
        FieldDescriptor.Builder builder88 = FieldDescriptor.builder("onDeviceImageCaptioningLoadLogEvent");
        zzfc zzfcVar88 = new zzfc();
        zzfcVar88.zza(91);
        K0 = builder88.withProperty(zzfcVar88.zzb()).build();
        FieldDescriptor.Builder builder89 = FieldDescriptor.builder("onDeviceImageCaptioningInferenceLogEvent");
        zzfc zzfcVar89 = new zzfc();
        zzfcVar89.zza(92);
        L0 = builder89.withProperty(zzfcVar89.zzb()).build();
        FieldDescriptor.Builder builder90 = FieldDescriptor.builder("aggregatedOnDeviceImageCaptioningInferenceLogEvent");
        zzfc zzfcVar90 = new zzfc();
        zzfcVar90.zza(93);
        M0 = builder90.withProperty(zzfcVar90.zzb()).build();
        FieldDescriptor.Builder builder91 = FieldDescriptor.builder("onDeviceDocumentDetectionCreateLogEvent");
        zzfc zzfcVar91 = new zzfc();
        zzfcVar91.zza(94);
        N0 = builder91.withProperty(zzfcVar91.zzb()).build();
        FieldDescriptor.Builder builder92 = FieldDescriptor.builder("onDeviceDocumentDetectionLoadLogEvent");
        zzfc zzfcVar92 = new zzfc();
        zzfcVar92.zza(95);
        O0 = builder92.withProperty(zzfcVar92.zzb()).build();
        FieldDescriptor.Builder builder93 = FieldDescriptor.builder("onDeviceDocumentDetectionLogEvent");
        zzfc zzfcVar93 = new zzfc();
        zzfcVar93.zza(96);
        P0 = builder93.withProperty(zzfcVar93.zzb()).build();
        FieldDescriptor.Builder builder94 = FieldDescriptor.builder("aggregatedOnDeviceDocumentDetectionLogEvent");
        zzfc zzfcVar94 = new zzfc();
        zzfcVar94.zza(97);
        Q0 = builder94.withProperty(zzfcVar94.zzb()).build();
        FieldDescriptor.Builder builder95 = FieldDescriptor.builder("onDeviceDocumentCroppingCreateLogEvent");
        zzfc zzfcVar95 = new zzfc();
        zzfcVar95.zza(98);
        R0 = builder95.withProperty(zzfcVar95.zzb()).build();
        FieldDescriptor.Builder builder96 = FieldDescriptor.builder("onDeviceDocumentCroppingLoadLogEvent");
        zzfc zzfcVar96 = new zzfc();
        zzfcVar96.zza(99);
        S0 = builder96.withProperty(zzfcVar96.zzb()).build();
        FieldDescriptor.Builder builder97 = FieldDescriptor.builder("onDeviceDocumentCroppingLogEvent");
        zzfc zzfcVar97 = new zzfc();
        zzfcVar97.zza(100);
        T0 = builder97.withProperty(zzfcVar97.zzb()).build();
        FieldDescriptor.Builder builder98 = FieldDescriptor.builder("aggregatedOnDeviceDocumentCroppingLogEvent");
        zzfc zzfcVar98 = new zzfc();
        zzfcVar98.zza(101);
        U0 = builder98.withProperty(zzfcVar98.zzb()).build();
        FieldDescriptor.Builder builder99 = FieldDescriptor.builder("onDeviceDocumentEnhancementCreateLogEvent");
        zzfc zzfcVar99 = new zzfc();
        zzfcVar99.zza(102);
        V0 = builder99.withProperty(zzfcVar99.zzb()).build();
        FieldDescriptor.Builder builder100 = FieldDescriptor.builder("onDeviceDocumentEnhancementLoadLogEvent");
        zzfc zzfcVar100 = new zzfc();
        zzfcVar100.zza(103);
        W0 = builder100.withProperty(zzfcVar100.zzb()).build();
        FieldDescriptor.Builder builder101 = FieldDescriptor.builder("onDeviceDocumentEnhancementLogEvent");
        zzfc zzfcVar101 = new zzfc();
        zzfcVar101.zza(104);
        X0 = builder101.withProperty(zzfcVar101.zzb()).build();
        FieldDescriptor.Builder builder102 = FieldDescriptor.builder("aggregatedOnDeviceDocumentEnhancementLogEvent");
        zzfc zzfcVar102 = new zzfc();
        zzfcVar102.zza(105);
        Y0 = builder102.withProperty(zzfcVar102.zzb()).build();
        FieldDescriptor.Builder builder103 = FieldDescriptor.builder("scannerAutoZoomEvent");
        zzfc zzfcVar103 = new zzfc();
        zzfcVar103.zza(106);
        Z0 = builder103.withProperty(zzfcVar103.zzb()).build();
        FieldDescriptor.Builder builder104 = FieldDescriptor.builder("lowLightAutoExposureComputationEvent");
        zzfc zzfcVar104 = new zzfc();
        zzfcVar104.zza(107);
        a1 = builder104.withProperty(zzfcVar104.zzb()).build();
        FieldDescriptor.Builder builder105 = FieldDescriptor.builder("lowLightFrameProcessEvent");
        zzfc zzfcVar105 = new zzfc();
        zzfcVar105.zza(108);
        b1 = builder105.withProperty(zzfcVar105.zzb()).build();
        FieldDescriptor.Builder builder106 = FieldDescriptor.builder("lowLightSceneDetectionEvent");
        zzfc zzfcVar106 = new zzfc();
        zzfcVar106.zza(109);
        c1 = builder106.withProperty(zzfcVar106.zzb()).build();
    }

    @Override // com.google.firebase.encoders.ObjectEncoder
    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) throws IOException {
        zzpn zzpnVar = (zzpn) obj;
        ObjectEncoderContext objectEncoderContext = (ObjectEncoderContext) obj2;
        objectEncoderContext.add(b, zzpnVar.zzg());
        objectEncoderContext.add(c, zzpnVar.zzc());
        objectEncoderContext.add(d, (Object) null);
        objectEncoderContext.add(e, zzpnVar.zzb());
        objectEncoderContext.add(f, (Object) null);
        objectEncoderContext.add(g, (Object) null);
        objectEncoderContext.add(h, (Object) null);
        objectEncoderContext.add(i, (Object) null);
        objectEncoderContext.add(j, (Object) null);
        objectEncoderContext.add(k, (Object) null);
        objectEncoderContext.add(l, (Object) null);
        objectEncoderContext.add(m, (Object) null);
        objectEncoderContext.add(n, zzpnVar.zzd());
        objectEncoderContext.add(o, zzpnVar.zze());
        objectEncoderContext.add(p, (Object) null);
        objectEncoderContext.add(q, (Object) null);
        objectEncoderContext.add(r, (Object) null);
        objectEncoderContext.add(s, (Object) null);
        objectEncoderContext.add(t, (Object) null);
        objectEncoderContext.add(u, (Object) null);
        objectEncoderContext.add(v, (Object) null);
        objectEncoderContext.add(w, (Object) null);
        objectEncoderContext.add(x, (Object) null);
        objectEncoderContext.add(y, (Object) null);
        objectEncoderContext.add(z, (Object) null);
        objectEncoderContext.add(A, (Object) null);
        objectEncoderContext.add(B, (Object) null);
        objectEncoderContext.add(C, (Object) null);
        objectEncoderContext.add(D, (Object) null);
        objectEncoderContext.add(E, (Object) null);
        objectEncoderContext.add(F, (Object) null);
        objectEncoderContext.add(G, (Object) null);
        objectEncoderContext.add(H, (Object) null);
        objectEncoderContext.add(I, (Object) null);
        objectEncoderContext.add(J, (Object) null);
        objectEncoderContext.add(K, (Object) null);
        objectEncoderContext.add(L, (Object) null);
        objectEncoderContext.add(M, (Object) null);
        objectEncoderContext.add(N, (Object) null);
        objectEncoderContext.add(O, (Object) null);
        objectEncoderContext.add(P, (Object) null);
        objectEncoderContext.add(Q, (Object) null);
        objectEncoderContext.add(R, (Object) null);
        objectEncoderContext.add(S, zzpnVar.zza());
        objectEncoderContext.add(T, (Object) null);
        objectEncoderContext.add(U, (Object) null);
        objectEncoderContext.add(V, (Object) null);
        objectEncoderContext.add(W, (Object) null);
        objectEncoderContext.add(X, (Object) null);
        objectEncoderContext.add(Y, (Object) null);
        objectEncoderContext.add(Z, (Object) null);
        objectEncoderContext.add(a0, (Object) null);
        objectEncoderContext.add(b0, (Object) null);
        objectEncoderContext.add(c0, (Object) null);
        objectEncoderContext.add(d0, (Object) null);
        objectEncoderContext.add(e0, (Object) null);
        objectEncoderContext.add(f0, (Object) null);
        objectEncoderContext.add(g0, (Object) null);
        objectEncoderContext.add(h0, (Object) null);
        objectEncoderContext.add(i0, (Object) null);
        objectEncoderContext.add(j0, (Object) null);
        objectEncoderContext.add(k0, (Object) null);
        objectEncoderContext.add(l0, (Object) null);
        objectEncoderContext.add(m0, (Object) null);
        objectEncoderContext.add(n0, (Object) null);
        objectEncoderContext.add(o0, (Object) null);
        objectEncoderContext.add(p0, (Object) null);
        objectEncoderContext.add(q0, (Object) null);
        objectEncoderContext.add(r0, (Object) null);
        objectEncoderContext.add(s0, (Object) null);
        objectEncoderContext.add(t0, (Object) null);
        objectEncoderContext.add(u0, (Object) null);
        objectEncoderContext.add(v0, (Object) null);
        objectEncoderContext.add(w0, (Object) null);
        objectEncoderContext.add(x0, (Object) null);
        objectEncoderContext.add(y0, (Object) null);
        objectEncoderContext.add(z0, (Object) null);
        objectEncoderContext.add(A0, (Object) null);
        objectEncoderContext.add(B0, (Object) null);
        objectEncoderContext.add(C0, (Object) null);
        objectEncoderContext.add(D0, (Object) null);
        objectEncoderContext.add(E0, (Object) null);
        objectEncoderContext.add(F0, (Object) null);
        objectEncoderContext.add(G0, (Object) null);
        objectEncoderContext.add(H0, (Object) null);
        objectEncoderContext.add(I0, (Object) null);
        objectEncoderContext.add(J0, (Object) null);
        objectEncoderContext.add(K0, (Object) null);
        objectEncoderContext.add(L0, (Object) null);
        objectEncoderContext.add(M0, (Object) null);
        objectEncoderContext.add(N0, (Object) null);
        objectEncoderContext.add(O0, (Object) null);
        objectEncoderContext.add(P0, (Object) null);
        objectEncoderContext.add(Q0, (Object) null);
        objectEncoderContext.add(R0, (Object) null);
        objectEncoderContext.add(S0, (Object) null);
        objectEncoderContext.add(T0, (Object) null);
        objectEncoderContext.add(U0, (Object) null);
        objectEncoderContext.add(V0, (Object) null);
        objectEncoderContext.add(W0, (Object) null);
        objectEncoderContext.add(X0, (Object) null);
        objectEncoderContext.add(Y0, (Object) null);
        objectEncoderContext.add(Z0, zzpnVar.zzf());
        objectEncoderContext.add(a1, (Object) null);
        objectEncoderContext.add(b1, (Object) null);
        objectEncoderContext.add(c1, (Object) null);
    }
}
