package com.coveiot.sdk.ble.api.error;
/* loaded from: classes9.dex */
public enum Type {
    DEVICE_NOT_CONNECTED,
    BLUETOOTH_DISABLED,
    SERVICE_NOT_RUNNING,
    LOCATION_PERMISSION_NEEDED,
    SCANNING_INPROGRESS,
    BAND_ALREADY_CONNECTED,
    CONNECTION_IN_PROGRESS,
    COMMAND_REQUEST_ERROR,
    COMMAND_WRITE_FAILED,
    COMMAND_TIMED_OUT,
    WATCH_RESPONSE_FAILED,
    WATCH_BUSY,
    SERVICE_BUSY,
    GET_FIRMWARE_CAPABILITY_FAILED
}
