package com.coveiot.android.matrixsdk.error;
/* loaded from: classes5.dex */
public enum MatrixErrorType {
    DEVICE_NOT_CONNECTED,
    BLUETOOTH_DISABLED,
    SERVICE_NOT_RUNNING,
    LOCATION_PERMISSION_NEEDED,
    SCANNING_INPROGRESS,
    BAND_ALREADY_CONNECTED,
    CONNECTION_IN_PROGRESS,
    COMMAND_REQUEST_ERROR,
    BAND_INSTRUCTION_NOT_FOLLOWED,
    LEAD_CONNECTION_FAILED,
    COMMAND_TIME_OUT
}
