package com.coveiot.android.leonardo.utils;

import com.coveiot.android.activitymodes.utils.WorkoutConstants;
import com.coveiot.android.bleabstract.Constants;
import com.coveiot.android.dashboard2.util.Dashboard2Constants;
import com.coveiot.android.fitnesschallenges.utils.FitnessChallengeConstants;
import com.coveiot.android.leonardo.onboarding.phonevalidation.fragments.FragmentEnterPhoneNumber;
import com.coveiot.android.watchfaceui.constants.WatchfaceConstants;
import com.coveiot.coveaccess.CoveApi;
import com.coveiot.covepreferences.HelpManager;
import com.coveiot.utils.utility.UtilConstants;
import com.goodix.ble.libcomx.util.HexStringBuilder;
import com.google.firebase.analytics.FirebaseAnalytics;
import com.jstyle.blesdk1860.constant.BleConst;
import com.szabh.smable3.entity.BleDeviceInfo;
import kotlin.jvm.internal.Intrinsics;
import org.jetbrains.annotations.NotNull;
/* loaded from: classes5.dex */
public enum AppConstants {
    EMPTY_STRING(""),
    EMPTY_SPACE(HexStringBuilder.DEFAULT_SEPARATOR),
    ZERO(BleConst.GetDeviceTime),
    SHARE_SCREEN_TYPE("share_screen"),
    IS_DAY_SELECTED("is_day_selected"),
    NOTIFICATION_ID("1"),
    HUNDRED("100"),
    WEATHER_INTERVAL(BleConst.EnterActivityMode),
    SURVEY("survey"),
    CHANNEL_ID(Constants.NOTIFICATION_CHANNEL_ID),
    IS_CUSTOMNOTIFICATION("customnotification"),
    USER_ID_KEY("userid"),
    FCM_REGISTRATION_ID_KEY("fcm-reg-key"),
    GYM_SPA_DETAIL("gym_spa_detail"),
    PLACE_TYPE("place_type"),
    DFUTARG("DfuTarg"),
    INTENT_EXTRA_URL(WorkoutConstants.INTENT_EXTRA_URL),
    EULA_URL("https://docs.coveiot.com/kaha/eula.html"),
    WEBSITE_URL("http://static.coveiot.com/random/wip.html?text=Coming%20soon"),
    PRIVACY_POLICY_URL("https://docs.coveiot.com/kaha/privacy-policy.html"),
    USER_MANUAL_URL("https://static.coveiot.com/borrelly/user-manual-v1.html"),
    FAQ_URL("https://static.coveiot.com/borrelly/faq-v1.html"),
    SUPPORT_URL("https://static.coveiot.com/borrelly/support.html"),
    WARRANTY_CARD("https://static.coveiot.com/borrelly/warranty-v1.html"),
    TROUBLESHOOT_URL("https://static.coveiot.com/borrelly/troubleshoot-v2.html"),
    COVEIOT_URL("https://www.boat-lifestyle.com"),
    CONSENT_EULA_URL("https://static.coveiot.com/cove-health/consent-eula.html"),
    CONSENT_PRIVACY_POLICY_URL("https://static.coveiot.com/cove-health/consent-privacy-policy.html"),
    USA_COUNTRY_INDEX("2"),
    DEFAULT_COUNTRY_INDEX(BleConst.GetDeviceTime),
    PHONE_NUMBER("phone_number"),
    INTENT_EXTRA_TITLE(WorkoutConstants.INTENT_EXTRA_TITLE),
    INTENT_EXTRA_IS_FROM_FAQ("INTENT_EXTRA_IS_FROM_FAQ"),
    PROFILE_IMAGE_FILENAME("_profile_img.jpg"),
    PHONE_VALID_PHONENO("phone_valid_phoneno"),
    COUNTRYCODE_PHONENO("countrycode_phoneno"),
    SHARE_DATA("share_data"),
    PHONE_NO("phone_no"),
    COUNTRY_CODE("country_code"),
    SERVICE_TYPE_LIST("service_type_list"),
    DEFAULT_SERVICE_TYPE("default_service_type"),
    SCAN_FILTER_DEVICE("Cove_V2"),
    SCAN_FILTER_IDOC("IDOCWATCH_V2"),
    SCAN_FILTER_v7("C_BA1011V11"),
    SCAN_FILTER_v7_BLUERIDGE("C1_BA1V1"),
    SCAN_FILTER_v7_OPENAMERICA("C4_BA1V1"),
    SCAN_FILTER_v7_COVE("C3_BA1V1"),
    SCAN_FILTER_CZ1_COVE("C3_WA7V1"),
    SCAN_FILTER_WAVEPRO("WAVEPRO"),
    SCAN_FILTER_WAVEPLUS("WAVEPLUS"),
    SCAN_FILTER_XTENDSPORT("XTENDSPORT"),
    SCAN_FILTER_WAVEPRIME("WAVEPRIME"),
    SCAN_FILTER_WAVEELITE("WAVEELITE"),
    SCAN_FILTER_CA("CA_0"),
    SCAN_FILTER_v7_LAVA("L1_BA1V1"),
    SCAN_FILTER_DEVICE_SMART_T_TEE("O8_TE"),
    SCAN_FILTER_CA_0("CA_0"),
    SCAN_FILTER_CA_3("COSMOS"),
    SCAN_FILTER_STORMPRO("STORMPRO"),
    SCAN_FILTER_XTENDPRO("XTENDPRO"),
    SCAN_FILTER_PRIMIA_VOICE("PRIMIAV"),
    SCAN_FILTER_LOOP_CALL_PRO("LCALLPRO"),
    SCAN_FILTER_LOOP_CONNECT_PRO("LCONNECTPRO"),
    CALORIES_FIT(" - calories"),
    DISTANCE_FIT(" - distance"),
    HEART_RATE_FIT(" - heart rate"),
    HEART_RATE_SUMMARY_FIT(" - heart rate summary"),
    SLEEP_FIT(" - sleep session"),
    SPO2_FIT(" - spo2 data"),
    BODY_TEMPERATURE_FIT(" - body temperature data"),
    STEPSCOUNT_FIT(" - step count"),
    EMPTY_HYPHEN("-"),
    SESSION_EXPIRE("401"),
    MALE("Male"),
    FEMALE(Dashboard2Constants.FEMALE),
    OTHER("Other"),
    HEIGHT_START_RANGE("70"),
    HEIGHT_END_RANGE("272"),
    STRIDE_LENGTH_START_RANGE(BleConst.GetDetailActivityData),
    STRIDE_LENGTH_END_RANGE("150"),
    HEIGHT_DEFAULT("165"),
    WEIGHT_START_RANGE(BleConst.GetDeviceMacAddress),
    WEIGHT_START_RANGE_IMPERIAL(BleConst.SetSedentaryReminder),
    WEIGHT_END_RANGE("450"),
    WEIGHT_END_RANGE_IMPERIAL("922"),
    WEIGHT_DEFAULT(BleConst.GetMusicControl),
    LEONARDO_FIRMWARE_FILE_NAME("Leonardo_FW"),
    JSTYLE_FIRMWARE_FILE_NAME("Jstyle_FW"),
    JSTYLE_AGPS_FILE_NAME(Dashboard2Constants.JSTYLE_AGPS_FILE_NAME),
    SMA_FIRMWARE_FILE_NAME("Sma_FW"),
    MOYANG_FIRMWARE_FILE_NAME("Moyang_FW"),
    MATRIX_FIRMWARE_FILE_NAME("fw_matrix"),
    IDO_FIRMWARE_FILE_NAME("fw_ido"),
    TOUCH_FIRMWARE_FILE_NAME("fw_touch"),
    EASTAPEX_FIRMWARE_FILE_NAME("fw_eastapex"),
    PS1_FIRMWARE_FILE_NAME("fw_ps1"),
    BLOCK("BLOCK"),
    NOTIFY("NOTIFY"),
    ENFORCE("ENFORCE"),
    OPTIONAL("OPTIONAL"),
    DAY_INTERVAL_FOR_APP_UPDATE("1"),
    FIRMWARE_BEAN("firmware_bean"),
    FIRMWARE_FILE("firmware_file"),
    DAY("DAY"),
    WEEK("WEEK"),
    MONTH("MONTH"),
    HR_EMPTY("---"),
    BP_EMPTY("--/--"),
    ENABLE_NOTIFICATION_LISTENERS("enabled_notification_listeners"),
    IS_MODIFY_PHONE_NO("is_modify_phone_no"),
    NOTIFICATION_SETTING("android.settings.ACTION_NOTIFICATION_LISTENER_SETTINGS"),
    DEFAULT_AGE(BleConst.BackHomeView),
    COVEJS_INTERFACE_URL("https://static.cove.kahaapi.com/js-interface/index.html"),
    RUN_SESSION_TARGET("run_session_target"),
    NOTIFICATION_TYPE("FCM_NOTIFICATION_TYPE"),
    PHONE_FINDER_NOTIFICATION_ID(UtilConstants.ID_NOTIFICATION_CHANNEL),
    FITNESS_LIVE_SOCKET_URL(CoveApi.getInstance().getBaseUrl() + "fitness/live"),
    FITNESS_LIVE_SOCKET_URL_DEMO("https://qa.cove.kahaapi.com/fitness/live"),
    INTENT_FILTER_STRIDE_SPLASH("BOAT_SPLASHf"),
    SCAN_FILTER_DEVICE_1790("j1790"),
    SCAN_FILTER_DEVICE_1810G("j1810"),
    SCAN_FILTER_DEVICE_1963D("1963"),
    SCAN_FILTER_DEVICE_1963YH("1963"),
    SCAN_FILTER_DEVICE_ARM("arm"),
    SCAN_FILTER_DEVICE_COVE_BA("cove_ba1003v11"),
    SCAN_FILTER_DEVICE_C_BA1010V11("c_ba1010v11"),
    SCAN_FILTER_DEVICE_F_WA1002V11("f_wa1002v11"),
    SCAN_FILTER_DEVICE_O8_WA1V1("o8_wa1v1"),
    SCAN_FILTER_DEVICE_TX_WA1V1("TX_WA1V1"),
    SCAN_FILTER_DEVICE_COVE9("cove9"),
    SCAN_FILTER_DEVICE_CO19("co19"),
    SCAN_FILTER_DEVICE_COVE_BA1009("cove_ba1009v11"),
    SCAN_FILTER_DEVICE_SPO2("PC"),
    SCAN_FILTER_DEVICE_COVE_("cove_"),
    SCAN_FILTER_DEVICE_C_("c_"),
    SCAN_FILTER_DEVICE_O8_BA1V1("O8_BA1V1"),
    SCAN_FILTER_DEVICE_O8_WA2V1("O8_WA2V1"),
    SCAN_FILTER_DEVICE_1860("GPSfit Pro 1860"),
    SCAN_FILTER_DEVICE_WANDERER("WANDERER"),
    MIN_AGE_RESTRICTION("3"),
    DEFAULT_COUNTRY_CODE("91,IN"),
    DEFAULT_STEPS_GOAL("10000"),
    IS_FROM_SCHEDULER(Dashboard2Constants.IS_FROM_SCHEDULER),
    IS_FROM_HOME("IS_FROM_HOME"),
    COVE9_PROFILEPIC_FOLDER("boAt Crest"),
    SCAN_FILTER_DEVICE_SMA_F2("F2"),
    SCAN_FILTER_DEVICE_SMA_MERCURY("MERCURY"),
    SCAN_FILTER_DEVICE_SMA_S10("MC-GPSWATCH_LE"),
    SCAN_FILTER_DEVICE_MOYANG_Y20("Y20"),
    SCAN_FILTER_DEVICE_MOYANG_VERTEX("VERTEX"),
    SCAN_FILTER_DEVICE_SMA_S12(BleDeviceInfo.PROTOTYPE_R9),
    SCAN_FILTER_DEVICE_IDO_SELECT("SELECT"),
    SCAN_FILTER_DEVICE_IDO_WAVE_SELECT("WAVESELECT"),
    SCAN_FILTER_DEVICE_IDO_CONNECT("CONNECT"),
    SCAN_FILTER_DEVICE_IDO_WAVE_CONNECT("WAVECONNECT"),
    SCAN_FILTER_DEVICE_SMA_S12_2("PRIMIA"),
    SCAN_FILTER_DEVICE_MATRIX_LA07("HLA07"),
    SCAN_FILTER_DEVICE_MATRIX("MATRIX"),
    SCAN_FILTER_DEVICE_MOYANG_WAVEFIT("WAVEFIT"),
    ONBOARDING(HelpManager.KEY_ONBOARDING),
    EDIT_LANGUAGE("editlanguage"),
    PAGE_TYPE("pagetype"),
    LEFT_HAND_WRIST(WatchfaceConstants.LEFT_HAND_WRIST),
    RIGHT_HAND_WRIST(WatchfaceConstants.RIGHT_HAND_WRIST),
    MILES(WatchfaceConstants.MILES),
    KILOMETERS(WatchfaceConstants.KILOMETERS),
    H12(WatchfaceConstants.H12),
    H24(WatchfaceConstants.H24),
    FAHRENHEIT(WatchfaceConstants.FAHRENHEIT),
    CELSIUS(WatchfaceConstants.CELSIUS),
    HEART_RATE(WatchfaceConstants.HEART_RATE),
    BP(WatchfaceConstants.BP),
    ACTIVITY_MODE(WatchfaceConstants.ACTIVITY_MODE),
    PHONE_FINDER(WatchfaceConstants.PHONE_FINDER),
    STRESS_LEVEL(WatchfaceConstants.STRESS_LEVEL),
    MUSIC(WatchfaceConstants.MUSIC),
    PORTRAIT(WatchfaceConstants.PORTRAIT),
    LOW_BATTERY_BROADCAST("LOW_BATTERY"),
    DEFAULT_AUTO_HR_INTERVAL(BleConst.EnterActivityMode),
    DEFAULT_AUTO_TEMEPERATURE_INTERVAL(BleConst.ReadHeartateSensorstatus),
    DEFAULT_CONTACT_TRACING_CMD_TIMEOUT(BleConst.CMD_Get_WorkOutReminder),
    DEFAULT_CONTACT_TRACING_CMD_TIMEOUT_MANUAL(BleConst.CMD_Set_Mac),
    SHIPBOOK_APP_ID(Dashboard2Constants.SHIPBOOK_APP_ID),
    SHIPBOOK_APP_KEY(Dashboard2Constants.SHIPBOOK_APP_KEY),
    ONBOARDING_VIDEO("onboarding_video"),
    VIDEO_TYPE("VIDEO_TYPE"),
    DEFAULT_SPO2_TMIN_IMEOUT_MANUAL("360"),
    CONSECUTIVE_LOW_COUNT_LIMIT(BleConst.GetDeviceInfo),
    DEFAULT_SPO2_REMINDER_INTERVAL(BleConst.GetDeviceName),
    MIN_FILTER_VALUE("34.9"),
    MAX_FILTER_VALUE("41.1"),
    DND_SUPPORTED_FW_HIGHER_VERSION("2"),
    DND_SUPPORTED_FW_LOWER_VERSION("0.60"),
    BUILD_FLAVOUR("build_flavour"),
    BUILD_TYPE("build_type"),
    ALL_ON(Dashboard2Constants.ALL_ON),
    ALL_OFF(Dashboard2Constants.ALL_OFF),
    SHIPBOOK_STATE(Dashboard2Constants.SHIPBOOK_STATE),
    SOURCE("Manual"),
    DRINK_WATER("DRINK_WATER"),
    TAKE_MEDICINE("TAKE_MEDICINE"),
    HAVE_FOOD("HAVE_FOOD"),
    SCREEN_NAME(FirebaseAnalytics.Param.SCREEN_NAME),
    OTHERS(""),
    CYCLE_START_RANGE(BleConst.GetDeviceName),
    CYCLE_END_RANGE(BleConst.ReadHeartateSensorstatus),
    PERIOD_OVULATION_REMINDER_START_RANGE("1"),
    PERIOD_OVULATION_REMINDER_END_RANGE("3"),
    PERIOD_START_RANGE("1"),
    PERIOD_END_RANGE(BleConst.GetDeviceName),
    AGPS_INTERVAL("1"),
    BATTERY_LEVEL_FOR_FW_UPDATE(BleConst.GPSControlCommand),
    MERCURY_SCREEN_TIMEOUT(BleConst.GetStepGoal),
    MUSIC_METADATA_BROADCAST_INTENT(Dashboard2Constants.MUSIC_METADATA_BROADCAST_INTENT),
    MUSIC_PLAYBACK_STATE_CHANGE_BROADCAST_INTENT(Dashboard2Constants.MUSIC_PLAYBACK_STATE_CHANGE_BROADCAST_INTENT),
    MEDIA_VOLUME_CHANGE_BROADCAST_INTENT("android.media.VOLUME_CHANGED_ACTION"),
    MUSIC_METADATA_KEY_TITLE("title"),
    MUSIC_METADATA_KEY_ARTIST(Dashboard2Constants.MUSIC_METADATA_KEY_ARTIST),
    MUSIC_METADATA_KEY_ALBUM(Dashboard2Constants.MUSIC_METADATA_KEY_ALBUM),
    MUSIC_APP_PLAYBACK_STATE_CHANGED(Dashboard2Constants.MUSIC_APP_PLAYBACK_STATE_CHANGED),
    SPO2_EMPTY("---"),
    MIN_SPO2_FILTER_VALUE(BleConst.GetDeviceTime),
    MAX_SPO2_FILTER_VALUE("100"),
    LWV_DEFAULT_START_HOUR(BleConst.GetDeviceTime),
    LWV_DEFAULT_START_MINUTE(BleConst.GetDeviceTime),
    LWV_DEFAULT_END_HOUR(BleConst.RealTimeStep),
    LWV_DEFAULT_END_MINUTE(BleConst.Sendmsg),
    LWV_DEFAULT_END_HOUR_CY1(BleConst.SetSedentaryReminder),
    LWV_DEFAULT_END_MINUTE_CY1(BleConst.GetDeviceTime),
    LWV_DEFAULT_START_HOUR_CY1(BleConst.SetStepGoal),
    LWV_DEFAULT_START_MINUTE_CY1(BleConst.GetDeviceTime),
    SCAN_FILTER_ARGUMENT_KEY("scanFilter"),
    SCAN_TIME_ON_DISCONNECTION(BleConst.CMD_Reset),
    SNOOZE_TIME_INTERVAL_KEY("snooze_interval"),
    SNOOZE_REPEAT_COUNT_KEY("snooze_count"),
    EXTRA_COUNTRY_SELECTED(FragmentEnterPhoneNumber.EXTRA_COUNTRY_SELECTED),
    EXTRA_COUNTRY_NAME_SELECTED(FragmentEnterPhoneNumber.EXTRA_COUNTRY_NAME_SELECTED),
    EXTRA_COUNTRY_TIMEZONE_SELECTED("extra_country_timezone_selected"),
    COUNTRY_CODE_RESULT("200"),
    TEST_SMS_TITLE("Test SMS notification"),
    TEST_SMS_CONTENT("This is a test message. Please acknowledge the same in the App"),
    DVC_NOTIFICATION_ISSUE("DVC_NOTIFICATION_ISSUE"),
    AMBIENT_SOUND_EMPTY("--"),
    WORKOUT_VIDEOS_FILTER("workout_videos_filter"),
    TWO_DASH_STRING("--"),
    FIRMWARE_UPDATE("firmware_update"),
    FCM_NOTIFICATION_TYPE("FCM_NOTIFICATION_TYPE"),
    DATA_SYNC_FAILURE_THRESHOLD("3"),
    SESSION_ID("SESSION_ID"),
    ACTIVITY_TYPE("ACTIVITY_TYPE"),
    CRICKET_BATTING("CRICKET_BATTING"),
    CRICKET_BOWLING("CRICKET_BOWLING"),
    ADD_TO_COMPARE("ADD_TO_COMPARE"),
    ADD_TO_COMPARE_TITLE("ADD_TO_COMPARE_TITLE"),
    ADD_TO_COMPARE_TIME("ADD_TO_COMPARE_TIME"),
    ADD_TO_COMPARE_HAND_TYPE("ADD_TO_COMPARE_HAND_TYPE"),
    CRICKET_FILTER_TYPE("Type"),
    CRICKET_FILTER_HAND("Hand"),
    CRICKET_FILTER_BOWLING_TYPE("Bowling Type"),
    BOWLING_FAST("Fast"),
    BOWLING_MEDIUM("Medium"),
    BOWLING_MEDIUM_PACE("Medium Pace"),
    BOWLING_SPIN("Spin"),
    IS_RUN_DIAGNOSTIC_FRAGMENT("IS_RUN_DIAGNOSTIC_FRAGMENT"),
    WORKOUT_TYPE("WORKOUT_TYPE"),
    DEVICE_FAMILY_WAVE("WAVE"),
    DEVICE_FAMILY_LUNAR("LUNAR"),
    DEVICE_FAMILY_XTEND("XTEND"),
    DEVICE_FAMILY_STORM("STORM"),
    DEVICE_FAMILY_ULTIMA("ULTIMA"),
    DEFAULT_USER_PROFILE_NAME("boAthead"),
    DEFAULT_USER_PROFILE_GENDER("MALE"),
    DEFAULT_USER_PROFILE_HEIGHT("165"),
    DEFAULT_USER_PROFILE_WEIGHT(BleConst.ReadHeartateSensorstatus),
    DEFAULT_CALORIE_GOAL("500"),
    DEFAULT_SLEEP_GOAL("28800"),
    DEFAULT_DISTANCE_GOAL("5000"),
    DEFAULT_EXCERSIE_DURATION_GOAL("1800"),
    NOT_AVAILABLE_EMAIL("notavailable@coveiot.com"),
    CARD_TYPE("CARD_TYPE"),
    CHALLENGE_ID(FitnessChallengeConstants.CHALLENGE_ID),
    CHALLENGE_TYPE(FitnessChallengeConstants.CHALLENGE_TYPE),
    BUTTON_C11N("BUTTON_C11N"),
    SHORT_PRESS(Dashboard2Constants.SHORT_PRESS),
    LONG_PRESS(Dashboard2Constants.LONG_PRESS),
    BUTTON_4H_POSITION(BleConst.GetDeviceInfo),
    NOTIFY_NAVIGATION_EVENT_BROADCAST_INTENT(Constants.NOTIFY_NAVIGATION_EVENT_BROADCAST_INTENT),
    REQUEST_NAVIGATION_EVENT_BROADCAST_INTENT(Constants.REQUEST_NAVIGATION_EVENT_BROADCAST_INTENT),
    REQUEST_NAVIGATION_FEATURE_CONTENT_BROADCAST_INTENT(Constants.REQUEST_NAVIGATION_FEATURE_CONTENT_BROADCAST_INTENT),
    REQUEST_NAVIGATION_STATUS_BROADCAST_INTENT(Constants.REQUEST_NAVIGATION_STATUS_BROADCAST_INTENT);
    
    @NotNull
    private String value;

    AppConstants(String str) {
        this.value = str;
    }

    @NotNull
    public final String getValue() {
        return this.value;
    }

    public final void setValue(@NotNull String str) {
        Intrinsics.checkNotNullParameter(str, "<set-?>");
        this.value = str;
    }
}
