package com.jieli.jl_bt_ota.constant;
/* loaded from: classes11.dex */
public class ErrorCode {
    public static final int ERR_NONE = 0;
    public static final int ERR_UNKNOWN = 1048575;
    public static final int SUB_ERR_AUTH_DEVICE = 20481;
    public static final int SUB_ERR_BLE_NOT_SUPPORT = 4098;
    public static final int SUB_ERR_BLUETOOTH_NOT_ENABLE = 4099;
    public static final int SUB_ERR_CHANGE_BLE_MTU = 4115;
    public static final int SUB_ERR_CHECK_RECEIVED_DATA_FAILED = 16389;
    public static final int SUB_ERR_CHECK_UPGRADE_FILE = 16387;
    public static final int SUB_ERR_DATA_FORMAT = 12292;
    public static final int SUB_ERR_DATA_NOT_FOUND = 20485;
    public static final int SUB_ERR_DEVICE_LOW_VOLTAGE = 16386;
    public static final int SUB_ERR_EDR_NOT_INIT = 4100;
    public static final int SUB_ERR_FILE_NOT_FOUND = 20484;
    public static final int SUB_ERR_HEADSET_NOT_IN_CHARGING_BIN = 16398;
    public static final int SUB_ERR_IO_EXCEPTION = 20486;
    public static final int SUB_ERR_OFFSET_OVER = 16388;
    public static final int SUB_ERR_OP_FAILED = 4113;
    public static final int SUB_ERR_OTA_FAILED = 16385;
    public static final int SUB_ERR_OTA_IN_HANDLE = 16392;
    public static final int SUB_ERR_PARAMETER = 4097;
    public static final int SUB_ERR_PARSE_DATA = 12293;
    public static final int SUB_ERR_RECONNECT_FAILED = 16402;
    public static final int SUB_ERR_RECONNECT_TIMEOUT = 16401;
    public static final int SUB_ERR_REMOTE_NOT_CONNECTED = 4114;
    public static final int SUB_ERR_RESPONSE_BAD_RESULT = 12298;
    public static final int SUB_ERR_RESPONSE_BAD_STATUS = 12296;
    public static final int SUB_ERR_SCAN_DEVICE_FAILED = 8194;
    public static final int SUB_ERR_SEND_FAILED = 12290;
    public static final int SUB_ERR_SEND_TIMEOUT = 12295;
    public static final int SUB_ERR_SYS_BUSY = 12291;
    public static final int SUB_ERR_TWS_NOT_CONNECT = 16397;
    public static final int SUB_ERR_UPGRADE_CMD_TIMEOUT = 16395;
    public static final int SUB_ERR_UPGRADE_DATA_LEN = 16393;
    public static final int SUB_ERR_UPGRADE_FILE_VERSION_SAME = 16396;
    public static final int SUB_ERR_UPGRADE_FLASH_READ = 16394;
    public static final int SUB_ERR_UPGRADE_KEY_NOT_MATCH = 16390;
    public static final int SUB_ERR_UPGRADE_SAME_FILE = 16399;
    public static final int SUB_ERR_UPGRADE_TYPE_NOT_MATCH = 16391;
    public static final int SUB_ERR_UPGRADE_UNKNOWN = 16400;
    public static final int SUB_ERR_WAITING_COMMAND_TIMEOUT = 12299;
}
