package com.google.android.gms.internal.mlkit_vision_common;

import com.google.firebase.encoders.FieldDescriptor;
import com.google.firebase.encoders.ObjectEncoder;
import com.google.firebase.encoders.ObjectEncoderContext;
import java.io.IOException;
/* loaded from: classes8.dex */
public final class d2 implements ObjectEncoder {
    public static final FieldDescriptor A;
    public static final FieldDescriptor A0;
    public static final FieldDescriptor B;
    public static final FieldDescriptor B0;
    public static final FieldDescriptor C;
    public static final FieldDescriptor C0;
    public static final FieldDescriptor D;
    public static final FieldDescriptor D0;
    public static final FieldDescriptor E;
    public static final FieldDescriptor E0;
    public static final FieldDescriptor F;
    public static final FieldDescriptor F0;
    public static final FieldDescriptor G;
    public static final FieldDescriptor G0;
    public static final FieldDescriptor H;
    public static final FieldDescriptor H0;
    public static final FieldDescriptor I;
    public static final FieldDescriptor I0;
    public static final FieldDescriptor J;
    public static final FieldDescriptor J0;
    public static final FieldDescriptor K;
    public static final FieldDescriptor K0;
    public static final FieldDescriptor L;
    public static final FieldDescriptor L0;
    public static final FieldDescriptor M;
    public static final FieldDescriptor M0;
    public static final FieldDescriptor N;
    public static final FieldDescriptor O;
    public static final FieldDescriptor P;
    public static final FieldDescriptor Q;
    public static final FieldDescriptor R;
    public static final FieldDescriptor S;
    public static final FieldDescriptor T;
    public static final FieldDescriptor U;
    public static final FieldDescriptor V;
    public static final FieldDescriptor W;
    public static final FieldDescriptor X;
    public static final FieldDescriptor Y;
    public static final FieldDescriptor Z;

    /* renamed from: a  reason: collision with root package name */
    public static final d2 f9654a = new d2();
    public static final FieldDescriptor a0;
    public static final FieldDescriptor b;
    public static final FieldDescriptor b0;
    public static final FieldDescriptor c;
    public static final FieldDescriptor c0;
    public static final FieldDescriptor d;
    public static final FieldDescriptor d0;
    public static final FieldDescriptor e;
    public static final FieldDescriptor e0;
    public static final FieldDescriptor f;
    public static final FieldDescriptor f0;
    public static final FieldDescriptor g;
    public static final FieldDescriptor g0;
    public static final FieldDescriptor h;
    public static final FieldDescriptor h0;
    public static final FieldDescriptor i;
    public static final FieldDescriptor i0;
    public static final FieldDescriptor j;
    public static final FieldDescriptor j0;
    public static final FieldDescriptor k;
    public static final FieldDescriptor k0;
    public static final FieldDescriptor l;
    public static final FieldDescriptor l0;
    public static final FieldDescriptor m;
    public static final FieldDescriptor m0;
    public static final FieldDescriptor n;
    public static final FieldDescriptor n0;
    public static final FieldDescriptor o;
    public static final FieldDescriptor o0;
    public static final FieldDescriptor p;
    public static final FieldDescriptor p0;
    public static final FieldDescriptor q;
    public static final FieldDescriptor q0;
    public static final FieldDescriptor r;
    public static final FieldDescriptor r0;
    public static final FieldDescriptor s;
    public static final FieldDescriptor s0;
    public static final FieldDescriptor t;
    public static final FieldDescriptor t0;
    public static final FieldDescriptor u;
    public static final FieldDescriptor u0;
    public static final FieldDescriptor v;
    public static final FieldDescriptor v0;
    public static final FieldDescriptor w;
    public static final FieldDescriptor w0;
    public static final FieldDescriptor x;
    public static final FieldDescriptor x0;
    public static final FieldDescriptor y;
    public static final FieldDescriptor y0;
    public static final FieldDescriptor z;
    public static final FieldDescriptor z0;

    static {
        FieldDescriptor.Builder builder = FieldDescriptor.builder("systemInfo");
        zzae zzaeVar = new zzae();
        zzaeVar.zza(1);
        b = builder.withProperty(zzaeVar.zzb()).build();
        FieldDescriptor.Builder builder2 = FieldDescriptor.builder("eventName");
        zzae zzaeVar2 = new zzae();
        zzaeVar2.zza(2);
        c = builder2.withProperty(zzaeVar2.zzb()).build();
        FieldDescriptor.Builder builder3 = FieldDescriptor.builder("isThickClient");
        zzae zzaeVar3 = new zzae();
        zzaeVar3.zza(37);
        d = builder3.withProperty(zzaeVar3.zzb()).build();
        FieldDescriptor.Builder builder4 = FieldDescriptor.builder("clientType");
        zzae zzaeVar4 = new zzae();
        zzaeVar4.zza(61);
        e = builder4.withProperty(zzaeVar4.zzb()).build();
        FieldDescriptor.Builder builder5 = FieldDescriptor.builder("modelDownloadLogEvent");
        zzae zzaeVar5 = new zzae();
        zzaeVar5.zza(3);
        f = builder5.withProperty(zzaeVar5.zzb()).build();
        FieldDescriptor.Builder builder6 = FieldDescriptor.builder("customModelLoadLogEvent");
        zzae zzaeVar6 = new zzae();
        zzaeVar6.zza(20);
        g = builder6.withProperty(zzaeVar6.zzb()).build();
        FieldDescriptor.Builder builder7 = FieldDescriptor.builder("customModelInferenceLogEvent");
        zzae zzaeVar7 = new zzae();
        zzaeVar7.zza(4);
        h = builder7.withProperty(zzaeVar7.zzb()).build();
        FieldDescriptor.Builder builder8 = FieldDescriptor.builder("customModelCreateLogEvent");
        zzae zzaeVar8 = new zzae();
        zzaeVar8.zza(29);
        i = builder8.withProperty(zzaeVar8.zzb()).build();
        FieldDescriptor.Builder builder9 = FieldDescriptor.builder("onDeviceFaceDetectionLogEvent");
        zzae zzaeVar9 = new zzae();
        zzaeVar9.zza(5);
        j = builder9.withProperty(zzaeVar9.zzb()).build();
        FieldDescriptor.Builder builder10 = FieldDescriptor.builder("onDeviceFaceLoadLogEvent");
        zzae zzaeVar10 = new zzae();
        zzaeVar10.zza(59);
        k = builder10.withProperty(zzaeVar10.zzb()).build();
        FieldDescriptor.Builder builder11 = FieldDescriptor.builder("onDeviceTextDetectionLogEvent");
        zzae zzaeVar11 = new zzae();
        zzaeVar11.zza(6);
        l = builder11.withProperty(zzaeVar11.zzb()).build();
        FieldDescriptor.Builder builder12 = FieldDescriptor.builder("onDeviceTextDetectionLoadLogEvent");
        zzae zzaeVar12 = new zzae();
        zzaeVar12.zza(79);
        m = builder12.withProperty(zzaeVar12.zzb()).build();
        FieldDescriptor.Builder builder13 = FieldDescriptor.builder("onDeviceBarcodeDetectionLogEvent");
        zzae zzaeVar13 = new zzae();
        zzaeVar13.zza(7);
        n = builder13.withProperty(zzaeVar13.zzb()).build();
        FieldDescriptor.Builder builder14 = FieldDescriptor.builder("onDeviceBarcodeLoadLogEvent");
        zzae zzaeVar14 = new zzae();
        zzaeVar14.zza(58);
        o = builder14.withProperty(zzaeVar14.zzb()).build();
        FieldDescriptor.Builder builder15 = FieldDescriptor.builder("onDeviceImageLabelCreateLogEvent");
        zzae zzaeVar15 = new zzae();
        zzaeVar15.zza(48);
        p = builder15.withProperty(zzaeVar15.zzb()).build();
        FieldDescriptor.Builder builder16 = FieldDescriptor.builder("onDeviceImageLabelLoadLogEvent");
        zzae zzaeVar16 = new zzae();
        zzaeVar16.zza(49);
        q = builder16.withProperty(zzaeVar16.zzb()).build();
        FieldDescriptor.Builder builder17 = FieldDescriptor.builder("onDeviceImageLabelDetectionLogEvent");
        zzae zzaeVar17 = new zzae();
        zzaeVar17.zza(18);
        r = builder17.withProperty(zzaeVar17.zzb()).build();
        FieldDescriptor.Builder builder18 = FieldDescriptor.builder("onDeviceObjectCreateLogEvent");
        zzae zzaeVar18 = new zzae();
        zzaeVar18.zza(26);
        s = builder18.withProperty(zzaeVar18.zzb()).build();
        FieldDescriptor.Builder builder19 = FieldDescriptor.builder("onDeviceObjectLoadLogEvent");
        zzae zzaeVar19 = new zzae();
        zzaeVar19.zza(27);
        t = builder19.withProperty(zzaeVar19.zzb()).build();
        FieldDescriptor.Builder builder20 = FieldDescriptor.builder("onDeviceObjectInferenceLogEvent");
        zzae zzaeVar20 = new zzae();
        zzaeVar20.zza(28);
        u = builder20.withProperty(zzaeVar20.zzb()).build();
        FieldDescriptor.Builder builder21 = FieldDescriptor.builder("onDevicePoseDetectionLogEvent");
        zzae zzaeVar21 = new zzae();
        zzaeVar21.zza(44);
        v = builder21.withProperty(zzaeVar21.zzb()).build();
        FieldDescriptor.Builder builder22 = FieldDescriptor.builder("onDeviceSegmentationLogEvent");
        zzae zzaeVar22 = new zzae();
        zzaeVar22.zza(45);
        w = builder22.withProperty(zzaeVar22.zzb()).build();
        FieldDescriptor.Builder builder23 = FieldDescriptor.builder("onDeviceSmartReplyLogEvent");
        zzae zzaeVar23 = new zzae();
        zzaeVar23.zza(19);
        x = builder23.withProperty(zzaeVar23.zzb()).build();
        FieldDescriptor.Builder builder24 = FieldDescriptor.builder("onDeviceLanguageIdentificationLogEvent");
        zzae zzaeVar24 = new zzae();
        zzaeVar24.zza(21);
        y = builder24.withProperty(zzaeVar24.zzb()).build();
        FieldDescriptor.Builder builder25 = FieldDescriptor.builder("onDeviceTranslationLogEvent");
        zzae zzaeVar25 = new zzae();
        zzaeVar25.zza(22);
        z = builder25.withProperty(zzaeVar25.zzb()).build();
        FieldDescriptor.Builder builder26 = FieldDescriptor.builder("cloudFaceDetectionLogEvent");
        zzae zzaeVar26 = new zzae();
        zzaeVar26.zza(8);
        A = builder26.withProperty(zzaeVar26.zzb()).build();
        FieldDescriptor.Builder builder27 = FieldDescriptor.builder("cloudCropHintDetectionLogEvent");
        zzae zzaeVar27 = new zzae();
        zzaeVar27.zza(9);
        B = builder27.withProperty(zzaeVar27.zzb()).build();
        FieldDescriptor.Builder builder28 = FieldDescriptor.builder("cloudDocumentTextDetectionLogEvent");
        zzae zzaeVar28 = new zzae();
        zzaeVar28.zza(10);
        C = builder28.withProperty(zzaeVar28.zzb()).build();
        FieldDescriptor.Builder builder29 = FieldDescriptor.builder("cloudImagePropertiesDetectionLogEvent");
        zzae zzaeVar29 = new zzae();
        zzaeVar29.zza(11);
        D = builder29.withProperty(zzaeVar29.zzb()).build();
        FieldDescriptor.Builder builder30 = FieldDescriptor.builder("cloudImageLabelDetectionLogEvent");
        zzae zzaeVar30 = new zzae();
        zzaeVar30.zza(12);
        E = builder30.withProperty(zzaeVar30.zzb()).build();
        FieldDescriptor.Builder builder31 = FieldDescriptor.builder("cloudLandmarkDetectionLogEvent");
        zzae zzaeVar31 = new zzae();
        zzaeVar31.zza(13);
        F = builder31.withProperty(zzaeVar31.zzb()).build();
        FieldDescriptor.Builder builder32 = FieldDescriptor.builder("cloudLogoDetectionLogEvent");
        zzae zzaeVar32 = new zzae();
        zzaeVar32.zza(14);
        G = builder32.withProperty(zzaeVar32.zzb()).build();
        FieldDescriptor.Builder builder33 = FieldDescriptor.builder("cloudSafeSearchDetectionLogEvent");
        zzae zzaeVar33 = new zzae();
        zzaeVar33.zza(15);
        H = builder33.withProperty(zzaeVar33.zzb()).build();
        FieldDescriptor.Builder builder34 = FieldDescriptor.builder("cloudTextDetectionLogEvent");
        zzae zzaeVar34 = new zzae();
        zzaeVar34.zza(16);
        I = builder34.withProperty(zzaeVar34.zzb()).build();
        FieldDescriptor.Builder builder35 = FieldDescriptor.builder("cloudWebSearchDetectionLogEvent");
        zzae zzaeVar35 = new zzae();
        zzaeVar35.zza(17);
        J = builder35.withProperty(zzaeVar35.zzb()).build();
        FieldDescriptor.Builder builder36 = FieldDescriptor.builder("automlImageLabelingCreateLogEvent");
        zzae zzaeVar36 = new zzae();
        zzaeVar36.zza(23);
        K = builder36.withProperty(zzaeVar36.zzb()).build();
        FieldDescriptor.Builder builder37 = FieldDescriptor.builder("automlImageLabelingLoadLogEvent");
        zzae zzaeVar37 = new zzae();
        zzaeVar37.zza(24);
        L = builder37.withProperty(zzaeVar37.zzb()).build();
        FieldDescriptor.Builder builder38 = FieldDescriptor.builder("automlImageLabelingInferenceLogEvent");
        zzae zzaeVar38 = new zzae();
        zzaeVar38.zza(25);
        M = builder38.withProperty(zzaeVar38.zzb()).build();
        FieldDescriptor.Builder builder39 = FieldDescriptor.builder("isModelDownloadedLogEvent");
        zzae zzaeVar39 = new zzae();
        zzaeVar39.zza(39);
        N = builder39.withProperty(zzaeVar39.zzb()).build();
        FieldDescriptor.Builder builder40 = FieldDescriptor.builder("deleteModelLogEvent");
        zzae zzaeVar40 = new zzae();
        zzaeVar40.zza(40);
        O = builder40.withProperty(zzaeVar40.zzb()).build();
        FieldDescriptor.Builder builder41 = FieldDescriptor.builder("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzae zzaeVar41 = new zzae();
        zzaeVar41.zza(30);
        P = builder41.withProperty(zzaeVar41.zzb()).build();
        FieldDescriptor.Builder builder42 = FieldDescriptor.builder("aggregatedCustomModelInferenceLogEvent");
        zzae zzaeVar42 = new zzae();
        zzaeVar42.zza(31);
        Q = builder42.withProperty(zzaeVar42.zzb()).build();
        FieldDescriptor.Builder builder43 = FieldDescriptor.builder("aggregatedOnDeviceFaceDetectionLogEvent");
        zzae zzaeVar43 = new zzae();
        zzaeVar43.zza(32);
        R = builder43.withProperty(zzaeVar43.zzb()).build();
        FieldDescriptor.Builder builder44 = FieldDescriptor.builder("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzae zzaeVar44 = new zzae();
        zzaeVar44.zza(33);
        S = builder44.withProperty(zzaeVar44.zzb()).build();
        FieldDescriptor.Builder builder45 = FieldDescriptor.builder("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzae zzaeVar45 = new zzae();
        zzaeVar45.zza(34);
        T = builder45.withProperty(zzaeVar45.zzb()).build();
        FieldDescriptor.Builder builder46 = FieldDescriptor.builder("aggregatedOnDeviceObjectInferenceLogEvent");
        zzae zzaeVar46 = new zzae();
        zzaeVar46.zza(35);
        U = builder46.withProperty(zzaeVar46.zzb()).build();
        FieldDescriptor.Builder builder47 = FieldDescriptor.builder("aggregatedOnDeviceTextDetectionLogEvent");
        zzae zzaeVar47 = new zzae();
        zzaeVar47.zza(36);
        V = builder47.withProperty(zzaeVar47.zzb()).build();
        FieldDescriptor.Builder builder48 = FieldDescriptor.builder("aggregatedOnDevicePoseDetectionLogEvent");
        zzae zzaeVar48 = new zzae();
        zzaeVar48.zza(46);
        W = builder48.withProperty(zzaeVar48.zzb()).build();
        FieldDescriptor.Builder builder49 = FieldDescriptor.builder("aggregatedOnDeviceSegmentationLogEvent");
        zzae zzaeVar49 = new zzae();
        zzaeVar49.zza(47);
        X = builder49.withProperty(zzaeVar49.zzb()).build();
        FieldDescriptor.Builder builder50 = FieldDescriptor.builder("pipelineAccelerationInferenceEvents");
        zzae zzaeVar50 = new zzae();
        zzaeVar50.zza(69);
        Y = builder50.withProperty(zzaeVar50.zzb()).build();
        FieldDescriptor.Builder builder51 = FieldDescriptor.builder("remoteConfigLogEvent");
        zzae zzaeVar51 = new zzae();
        zzaeVar51.zza(42);
        Z = builder51.withProperty(zzaeVar51.zzb()).build();
        FieldDescriptor.Builder builder52 = FieldDescriptor.builder("inputImageConstructionLogEvent");
        zzae zzaeVar52 = new zzae();
        zzaeVar52.zza(50);
        a0 = builder52.withProperty(zzaeVar52.zzb()).build();
        FieldDescriptor.Builder builder53 = FieldDescriptor.builder("leakedHandleEvent");
        zzae zzaeVar53 = new zzae();
        zzaeVar53.zza(51);
        b0 = builder53.withProperty(zzaeVar53.zzb()).build();
        FieldDescriptor.Builder builder54 = FieldDescriptor.builder("cameraSourceLogEvent");
        zzae zzaeVar54 = new zzae();
        zzaeVar54.zza(52);
        c0 = builder54.withProperty(zzaeVar54.zzb()).build();
        FieldDescriptor.Builder builder55 = FieldDescriptor.builder("imageLabelOptionalModuleLogEvent");
        zzae zzaeVar55 = new zzae();
        zzaeVar55.zza(53);
        d0 = builder55.withProperty(zzaeVar55.zzb()).build();
        FieldDescriptor.Builder builder56 = FieldDescriptor.builder("languageIdentificationOptionalModuleLogEvent");
        zzae zzaeVar56 = new zzae();
        zzaeVar56.zza(54);
        e0 = builder56.withProperty(zzaeVar56.zzb()).build();
        FieldDescriptor.Builder builder57 = FieldDescriptor.builder("faceDetectionOptionalModuleLogEvent");
        zzae zzaeVar57 = new zzae();
        zzaeVar57.zza(60);
        f0 = builder57.withProperty(zzaeVar57.zzb()).build();
        FieldDescriptor.Builder builder58 = FieldDescriptor.builder("documentDetectionOptionalModuleLogEvent");
        zzae zzaeVar58 = new zzae();
        zzaeVar58.zza(85);
        g0 = builder58.withProperty(zzaeVar58.zzb()).build();
        FieldDescriptor.Builder builder59 = FieldDescriptor.builder("documentCroppingOptionalModuleLogEvent");
        zzae zzaeVar59 = new zzae();
        zzaeVar59.zza(86);
        h0 = builder59.withProperty(zzaeVar59.zzb()).build();
        FieldDescriptor.Builder builder60 = FieldDescriptor.builder("documentEnhancementOptionalModuleLogEvent");
        zzae zzaeVar60 = new zzae();
        zzaeVar60.zza(87);
        i0 = builder60.withProperty(zzaeVar60.zzb()).build();
        FieldDescriptor.Builder builder61 = FieldDescriptor.builder("nlClassifierOptionalModuleLogEvent");
        zzae zzaeVar61 = new zzae();
        zzaeVar61.zza(55);
        j0 = builder61.withProperty(zzaeVar61.zzb()).build();
        FieldDescriptor.Builder builder62 = FieldDescriptor.builder("nlClassifierClientLibraryLogEvent");
        zzae zzaeVar62 = new zzae();
        zzaeVar62.zza(56);
        k0 = builder62.withProperty(zzaeVar62.zzb()).build();
        FieldDescriptor.Builder builder63 = FieldDescriptor.builder("accelerationAllowlistLogEvent");
        zzae zzaeVar63 = new zzae();
        zzaeVar63.zza(57);
        l0 = builder63.withProperty(zzaeVar63.zzb()).build();
        FieldDescriptor.Builder builder64 = FieldDescriptor.builder("toxicityDetectionCreateEvent");
        zzae zzaeVar64 = new zzae();
        zzaeVar64.zza(62);
        m0 = builder64.withProperty(zzaeVar64.zzb()).build();
        FieldDescriptor.Builder builder65 = FieldDescriptor.builder("toxicityDetectionLoadEvent");
        zzae zzaeVar65 = new zzae();
        zzaeVar65.zza(63);
        n0 = builder65.withProperty(zzaeVar65.zzb()).build();
        FieldDescriptor.Builder builder66 = FieldDescriptor.builder("toxicityDetectionInferenceEvent");
        zzae zzaeVar66 = new zzae();
        zzaeVar66.zza(64);
        o0 = builder66.withProperty(zzaeVar66.zzb()).build();
        FieldDescriptor.Builder builder67 = FieldDescriptor.builder("barcodeDetectionOptionalModuleLogEvent");
        zzae zzaeVar67 = new zzae();
        zzaeVar67.zza(65);
        p0 = builder67.withProperty(zzaeVar67.zzb()).build();
        FieldDescriptor.Builder builder68 = FieldDescriptor.builder("customImageLabelOptionalModuleLogEvent");
        zzae zzaeVar68 = new zzae();
        zzaeVar68.zza(66);
        q0 = builder68.withProperty(zzaeVar68.zzb()).build();
        FieldDescriptor.Builder builder69 = FieldDescriptor.builder("codeScannerScanApiEvent");
        zzae zzaeVar69 = new zzae();
        zzaeVar69.zza(67);
        r0 = builder69.withProperty(zzaeVar69.zzb()).build();
        FieldDescriptor.Builder builder70 = FieldDescriptor.builder("codeScannerOptionalModuleEvent");
        zzae zzaeVar70 = new zzae();
        zzaeVar70.zza(68);
        s0 = builder70.withProperty(zzaeVar70.zzb()).build();
        FieldDescriptor.Builder builder71 = FieldDescriptor.builder("onDeviceExplicitContentCreateLogEvent");
        zzae zzaeVar71 = new zzae();
        zzaeVar71.zza(70);
        t0 = builder71.withProperty(zzaeVar71.zzb()).build();
        FieldDescriptor.Builder builder72 = FieldDescriptor.builder("onDeviceExplicitContentLoadLogEvent");
        zzae zzaeVar72 = new zzae();
        zzaeVar72.zza(71);
        u0 = builder72.withProperty(zzaeVar72.zzb()).build();
        FieldDescriptor.Builder builder73 = FieldDescriptor.builder("onDeviceExplicitContentInferenceLogEvent");
        zzae zzaeVar73 = new zzae();
        zzaeVar73.zza(72);
        v0 = builder73.withProperty(zzaeVar73.zzb()).build();
        FieldDescriptor.Builder builder74 = FieldDescriptor.builder("aggregatedOnDeviceExplicitContentLogEvent");
        zzae zzaeVar74 = new zzae();
        zzaeVar74.zza(73);
        w0 = builder74.withProperty(zzaeVar74.zzb()).build();
        FieldDescriptor.Builder builder75 = FieldDescriptor.builder("onDeviceFaceMeshCreateLogEvent");
        zzae zzaeVar75 = new zzae();
        zzaeVar75.zza(74);
        x0 = builder75.withProperty(zzaeVar75.zzb()).build();
        FieldDescriptor.Builder builder76 = FieldDescriptor.builder("onDeviceFaceMeshLoadLogEvent");
        zzae zzaeVar76 = new zzae();
        zzaeVar76.zza(75);
        y0 = builder76.withProperty(zzaeVar76.zzb()).build();
        FieldDescriptor.Builder builder77 = FieldDescriptor.builder("onDeviceFaceMeshLogEvent");
        zzae zzaeVar77 = new zzae();
        zzaeVar77.zza(76);
        z0 = builder77.withProperty(zzaeVar77.zzb()).build();
        FieldDescriptor.Builder builder78 = FieldDescriptor.builder("aggregatedOnDeviceFaceMeshLogEvent");
        zzae zzaeVar78 = new zzae();
        zzaeVar78.zza(77);
        A0 = builder78.withProperty(zzaeVar78.zzb()).build();
        FieldDescriptor.Builder builder79 = FieldDescriptor.builder("smartReplyOptionalModuleLogEvent");
        zzae zzaeVar79 = new zzae();
        zzaeVar79.zza(78);
        B0 = builder79.withProperty(zzaeVar79.zzb()).build();
        FieldDescriptor.Builder builder80 = FieldDescriptor.builder("textDetectionOptionalModuleLogEvent");
        zzae zzaeVar80 = new zzae();
        zzaeVar80.zza(80);
        C0 = builder80.withProperty(zzaeVar80.zzb()).build();
        FieldDescriptor.Builder builder81 = FieldDescriptor.builder("onDeviceImageQualityAnalysisCreateLogEvent");
        zzae zzaeVar81 = new zzae();
        zzaeVar81.zza(81);
        D0 = builder81.withProperty(zzaeVar81.zzb()).build();
        FieldDescriptor.Builder builder82 = FieldDescriptor.builder("onDeviceImageQualityAnalysisLoadLogEvent");
        zzae zzaeVar82 = new zzae();
        zzaeVar82.zza(82);
        E0 = builder82.withProperty(zzaeVar82.zzb()).build();
        FieldDescriptor.Builder builder83 = FieldDescriptor.builder("onDeviceImageQualityAnalysisLogEvent");
        zzae zzaeVar83 = new zzae();
        zzaeVar83.zza(83);
        F0 = builder83.withProperty(zzaeVar83.zzb()).build();
        FieldDescriptor.Builder builder84 = FieldDescriptor.builder("aggregatedOnDeviceImageQualityAnalysisLogEvent");
        zzae zzaeVar84 = new zzae();
        zzaeVar84.zza(84);
        G0 = builder84.withProperty(zzaeVar84.zzb()).build();
        FieldDescriptor.Builder builder85 = FieldDescriptor.builder("imageQualityAnalysisOptionalModuleLogEvent");
        zzae zzaeVar85 = new zzae();
        zzaeVar85.zza(88);
        H0 = builder85.withProperty(zzaeVar85.zzb()).build();
        FieldDescriptor.Builder builder86 = FieldDescriptor.builder("imageCaptioningOptionalModuleLogEvent");
        zzae zzaeVar86 = new zzae();
        zzaeVar86.zza(89);
        I0 = builder86.withProperty(zzaeVar86.zzb()).build();
        FieldDescriptor.Builder builder87 = FieldDescriptor.builder("onDeviceImageCaptioningCreateLogEvent");
        zzae zzaeVar87 = new zzae();
        zzaeVar87.zza(90);
        J0 = builder87.withProperty(zzaeVar87.zzb()).build();
        FieldDescriptor.Builder builder88 = FieldDescriptor.builder("onDeviceImageCaptioningLoadLogEvent");
        zzae zzaeVar88 = new zzae();
        zzaeVar88.zza(91);
        K0 = builder88.withProperty(zzaeVar88.zzb()).build();
        FieldDescriptor.Builder builder89 = FieldDescriptor.builder("onDeviceImageCaptioningInferenceLogEvent");
        zzae zzaeVar89 = new zzae();
        zzaeVar89.zza(92);
        L0 = builder89.withProperty(zzaeVar89.zzb()).build();
        FieldDescriptor.Builder builder90 = FieldDescriptor.builder("aggregatedOnDeviceImageCaptioningInferenceLogEvent");
        zzae zzaeVar90 = new zzae();
        zzaeVar90.zza(93);
        M0 = builder90.withProperty(zzaeVar90.zzb()).build();
    }

    @Override // com.google.firebase.encoders.ObjectEncoder
    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) throws IOException {
        zziy zziyVar = (zziy) obj;
        ObjectEncoderContext objectEncoderContext = (ObjectEncoderContext) obj2;
        objectEncoderContext.add(b, zziyVar.zzc());
        objectEncoderContext.add(c, zziyVar.zzb());
        objectEncoderContext.add(d, (Object) null);
        objectEncoderContext.add(e, (Object) null);
        objectEncoderContext.add(f, (Object) null);
        objectEncoderContext.add(g, (Object) null);
        objectEncoderContext.add(h, (Object) null);
        objectEncoderContext.add(i, (Object) null);
        objectEncoderContext.add(j, (Object) null);
        objectEncoderContext.add(k, (Object) null);
        objectEncoderContext.add(l, (Object) null);
        objectEncoderContext.add(m, (Object) null);
        objectEncoderContext.add(n, (Object) null);
        objectEncoderContext.add(o, (Object) null);
        objectEncoderContext.add(p, (Object) null);
        objectEncoderContext.add(q, (Object) null);
        objectEncoderContext.add(r, (Object) null);
        objectEncoderContext.add(s, (Object) null);
        objectEncoderContext.add(t, (Object) null);
        objectEncoderContext.add(u, (Object) null);
        objectEncoderContext.add(v, (Object) null);
        objectEncoderContext.add(w, (Object) null);
        objectEncoderContext.add(x, (Object) null);
        objectEncoderContext.add(y, (Object) null);
        objectEncoderContext.add(z, (Object) null);
        objectEncoderContext.add(A, (Object) null);
        objectEncoderContext.add(B, (Object) null);
        objectEncoderContext.add(C, (Object) null);
        objectEncoderContext.add(D, (Object) null);
        objectEncoderContext.add(E, (Object) null);
        objectEncoderContext.add(F, (Object) null);
        objectEncoderContext.add(G, (Object) null);
        objectEncoderContext.add(H, (Object) null);
        objectEncoderContext.add(I, (Object) null);
        objectEncoderContext.add(J, (Object) null);
        objectEncoderContext.add(K, (Object) null);
        objectEncoderContext.add(L, (Object) null);
        objectEncoderContext.add(M, (Object) null);
        objectEncoderContext.add(N, (Object) null);
        objectEncoderContext.add(O, (Object) null);
        objectEncoderContext.add(P, (Object) null);
        objectEncoderContext.add(Q, (Object) null);
        objectEncoderContext.add(R, (Object) null);
        objectEncoderContext.add(S, (Object) null);
        objectEncoderContext.add(T, (Object) null);
        objectEncoderContext.add(U, (Object) null);
        objectEncoderContext.add(V, (Object) null);
        objectEncoderContext.add(W, (Object) null);
        objectEncoderContext.add(X, (Object) null);
        objectEncoderContext.add(Y, (Object) null);
        objectEncoderContext.add(Z, (Object) null);
        objectEncoderContext.add(a0, zziyVar.zza());
        objectEncoderContext.add(b0, (Object) null);
        objectEncoderContext.add(c0, (Object) null);
        objectEncoderContext.add(d0, (Object) null);
        objectEncoderContext.add(e0, (Object) null);
        objectEncoderContext.add(f0, (Object) null);
        objectEncoderContext.add(g0, (Object) null);
        objectEncoderContext.add(h0, (Object) null);
        objectEncoderContext.add(i0, (Object) null);
        objectEncoderContext.add(j0, (Object) null);
        objectEncoderContext.add(k0, (Object) null);
        objectEncoderContext.add(l0, (Object) null);
        objectEncoderContext.add(m0, (Object) null);
        objectEncoderContext.add(n0, (Object) null);
        objectEncoderContext.add(o0, (Object) null);
        objectEncoderContext.add(p0, (Object) null);
        objectEncoderContext.add(q0, (Object) null);
        objectEncoderContext.add(r0, (Object) null);
        objectEncoderContext.add(s0, (Object) null);
        objectEncoderContext.add(t0, (Object) null);
        objectEncoderContext.add(u0, (Object) null);
        objectEncoderContext.add(v0, (Object) null);
        objectEncoderContext.add(w0, (Object) null);
        objectEncoderContext.add(x0, (Object) null);
        objectEncoderContext.add(y0, (Object) null);
        objectEncoderContext.add(z0, (Object) null);
        objectEncoderContext.add(A0, (Object) null);
        objectEncoderContext.add(B0, (Object) null);
        objectEncoderContext.add(C0, (Object) null);
        objectEncoderContext.add(D0, (Object) null);
        objectEncoderContext.add(E0, (Object) null);
        objectEncoderContext.add(F0, (Object) null);
        objectEncoderContext.add(G0, (Object) null);
        objectEncoderContext.add(H0, (Object) null);
        objectEncoderContext.add(I0, (Object) null);
        objectEncoderContext.add(J0, (Object) null);
        objectEncoderContext.add(K0, (Object) null);
        objectEncoderContext.add(L0, (Object) null);
        objectEncoderContext.add(M0, (Object) null);
    }
}
