package com.coveiot.android.remotecommandframework.alexa.utils;

import org.jetbrains.annotations.NotNull;
/* loaded from: classes6.dex */
public enum ErrorType {
    COMMAND_PARSING_FAILED("COMMAND_PARSING_FAILED"),
    DEVICE_NOT_CONNECTED("DEVICE_NOT_CONNECTED"),
    SYNC_IS_IN_PROGRESS("SYNC_IS_IN_PROGRESS"),
    COMMAND_NOT_SUPPORTED("COMMAND_NOT_SUPPORTED"),
    INVALID_COMMAND_DATA("INVALID_COMMAND_DATA"),
    COMMAND_NOT_IMPLEMENTED("COMMAND_NOT_IMPLEMENTED"),
    COMMAND_FAILED("COMMAND_FAILED"),
    SETTINGS_ALREADY_APPLIED("SETTINGS_ALREADY_APPLIED"),
    MAXIMUM_LIMIT_EXCEED("MAXIMUM_LIMIT_EXCEED"),
    COMMAND_TIMEOUT("COMMAND_TIMEOUT"),
    NOTIFICATION_ACCESS_NOT_ENABLED("NOTIFICATION_ACCESS_NOT_ENABLED"),
    DUPLICATE_REQUEST_RECEIVED("DUPLICATE_REQUEST_RECEIVED"),
    PREFERENCE_HANDLER_NOT_IMPLEMENTED("PREFERENCE_HANDLER_NOT_IMPLEMENTED"),
    PREFERENCE_HANDLER_PROVIDER_NOT_FOUND("PREFERENCE_HANDLER_PROVIDER_NOT_FOUND"),
    UNKNOWN_EXCEPTION_OCCURRED("UNKNOWN_EXCEPTION_OCCURRED"),
    BAD_REQUEST("BAD_REQUEST");
    
    @NotNull
    private final String type;

    ErrorType(String str) {
        this.type = str;
    }

    @NotNull
    public final String getType() {
        return this.type;
    }
}
