package com.coveiot.android.leonardo.more.models;

import kotlin.jvm.internal.Intrinsics;
import org.jetbrains.annotations.NotNull;
/* loaded from: classes5.dex */
public enum SportsType {
    SPORT_TYPE_INDOOR_WALK("Indoor walk"),
    SPORT_TYPE_OUTDOOR_WALK("Outdoor walk"),
    SPORT_TYPE_INDOOR_CYCLE("Indoor cycle"),
    SPORT_TYPE_INDOOR_RUN("Indoor run"),
    SPORT_TYPE_OUTDOOR_CYCLE("Outdoor cycle"),
    SPORT_TYPE_OUTDOOR_RUN("Outdoor run"),
    SPORT_TYPE_HIIT("HIIT"),
    SPORT_TYPE_CRICKET("Cricket"),
    SPORT_TYPE_DANCING("Dancing"),
    SPORT_TYPE_POOL_SWIM("Pool swim"),
    SPORT_TYPE_ELLIPTICAL("Ellipticals"),
    SPORT_TYPE_WATER_SWIM("Open water Swim"),
    SPORT_TYPE_OTHER("Others"),
    SPORT_TYPE_PILATES("Pilates"),
    SPORT_TYPE_ZUMBA("Zumba"),
    SPORT_TYPE_YOGA("Yoga"),
    SPORT_TYPE_ROWING_MACHINE("Rowing machine"),
    SPORT_TYPE_ONFOOT("Hiking"),
    SPORT_TYPE_SOCKER("Football"),
    SPORT_TYPE_FITNESS("Workout"),
    SPORT_TYPE_CORE_TRAINING("Core training"),
    SPORT_TYPE_ORGANIZE_AND_RELAX("Cooldown"),
    SPORT_TYPE_FUNCTIONAL_STRENGTH_TRAINING("Functional Strength training"),
    SPORT_TYPE_TRADITIONAL_STRENGTH_TRAINING("Traditional Strength training"),
    SPORT_TYPE_STEPPER("Stepper"),
    SPORT_TYPE_AEROBICS("Aerobics"),
    SPORT_TYPE_SIT_UPS("Sit Ups"),
    SPORT_TYPE_PLANK("Plank Support"),
    SPORT_TYPE_JUMPING_JACKS("Jumping jacks"),
    SPORT_TYPE_PULL_UP("Pull Ups"),
    SPORT_TYPE_PUSH_UPS("Push Ups"),
    SPORT_TYPE_SQUAT("Squat"),
    SPORT_TYPE_HIGH_KNEE_LIFT("High knee lift"),
    SPORT_TYPE_DUMBBELLS("Dumbbell"),
    SPORT_TYPE_BARBELL("Barbell"),
    SPORT_TYPE_BOXING("Boxing"),
    SPORT_TYPE_FREE_SPARRING("Free sparring"),
    SPORT_TYPE_HORIZONTAL_BAR("Horizontal bar"),
    SPORT_TYPE_PARALLEL_BARS("Parallel bars"),
    SPORT_TYPE_CARDIO_CRUISER("Cardio cruiser"),
    SPORT_TYPE_CLIMBING_MACHINE("Climbing machine"),
    SPORT_TYPE_BOWLING("Bowling"),
    SPORT_TYPE_TENNIS("Tennis"),
    SPORT_TYPE_TABLE_TENNIS("Table tennis"),
    SPORT_TYPE_GOLF("Golf"),
    SPORT_TYPE_BASKETBALL("Basketball"),
    SPORT_TYPE_BADMINTON("Badminton"),
    SPORT_TYPE_HOCKEY("Hockey"),
    SPORT_TYPE_AMERICAN_FOOTBALL("American football"),
    SPORT_TYPE_HANDBALL("Handball"),
    SPORT_TYPE_STREET_DANCE("Street dance"),
    SPORT_TYPE_CLIMBING("Climbing"),
    SPORT_TYPE_ROPE_SKIPPING("Rope Skipping"),
    SPORT_TYPE_STAIR_CLIMBING("Stair climbing"),
    SPORT_TYPE_SLEDDING("Sledding"),
    SPORT_TYPE_SKATING("Skating"),
    SPORT_TYPE_SURFING("Surfing"),
    SPORT_TYPE_SAIL_BOATING("Sailboating"),
    SPORT_TYPE_SKATEBOARDING("Skateboarding"),
    SPORT_TYPE_ROCK_CLIMBING("Rock climbing"),
    SPORT_TYPE_STRENGTH_TRAINING("Strength training"),
    SPORT_TYPE_FREE_WORKOUT("Free training"),
    SPORT_TYPE_HIKING("Hiking"),
    SPORT_TYPE_FOLK_DANCE("Folk dance"),
    SPORT_TYPE_HANDCAR("Hand Cycling"),
    SPORT_TYPE_KENDO("Kendo"),
    SPORT_TYPE_MEDITATION("Mind & body"),
    SPORT_TYPE_WRESTLING("Wrestling"),
    SPORT_TYPE_TAI_CHI("Tai Chi"),
    SPORT_TYPE_GYMNASTICS("Gymnastics"),
    SPORT_TYPE_TRACK_FIELD("Track field"),
    SPORT_TYPE_MARTIAL_ARTS("Martial arts"),
    SPORT_TYPE_PLAY("Play"),
    SPORT_TYPE_SNOW_SPORTS("Snow sports"),
    SPORT_TYPE_LACROSSE("Lacrosse"),
    SPORT_TYPE_SINGLE_BAR("Single Bar"),
    SPORT_TYPE_HULA_HOPE("Hula hoop"),
    SPORT_TYPE_DARTS("Darts"),
    SPORT_TYPE_ARCHERY("Archery"),
    SPORT_TYPE_HORSE_RIDING("Horse riding"),
    SPORT_TYPE_SHUTTLECOCK("Shuttlecock"),
    SPORT_TYPE_ICE_HOCKEY("Ice hockey"),
    SPORT_TYPE_WAIST_TRAINING("Waist training"),
    SPORT_TYPE_TREADMILL("Treadmill"),
    SPORT_TYPE_BATTLE_ROPE("Battle rope"),
    SPORT_TYPE_SMITH_MACHINE("Smith machine"),
    SPORT_TYPE_KABADDI("Kabaddi"),
    SPORT_TYPE_SHOT_PUT("Shot put"),
    SPORT_TYPE_SOLID_BALL("Solid ball"),
    SPORT_TYPE_JAVELIN("Javelin"),
    SPORT_TYPE_LONG_JUMP("Long jump"),
    SPORT_TYPE_HIGH_JUMP("High jump"),
    SPORT_TYPE_SQUARE_DANCE("Square dance"),
    SPORT_TYPE_KARTING("Karting"),
    SPORT_TYPE_DODGE_BALL("Dodge ball"),
    SPORT_TYPE_YOYO("Yoyo"),
    SPORT_TYPE_LOCKING("Locking"),
    SPORT_TYPE_BURPEES("Burpees"),
    SPORT_TYPE_BELLY_DANCE("Belly dance"),
    SPORT_TYPE_PARKOUR("Parkour"),
    SPORT_TYPE_JAZZ_DANCE("Jazz dance"),
    SPORT_TYPE_MODERN_DANCE("Modern dance"),
    SPORT_TYPE_CROSS_FITTING("Cross fit"),
    SPORT_TYPE_LATIN_DANCE("Latin dance"),
    SPORT_TYPE_POPING("Street Dance"),
    SPORT_TYPE_BALLET("Barre"),
    SPORT_TYPE_BASEBALL("Baseball"),
    SPORT_TYPE_RACQUETBALL("Racquetball"),
    SPORT_TYPE_CURLING("Curling"),
    SPORT_TYPE_HUNTING("Hunting"),
    SPORT_TYPE_SNOWBOARDING("Snowboarding"),
    SPORT_TYPE_FISHING("Fishing"),
    SPORT_TYPE_DISC_SPORTS("Disc sports"),
    SPORT_TYPE_RUGBY("Rugby"),
    SPORT_TYPE_SKI("SKI"),
    SPORT_TYPE_FITNESS_GAME("Fitness gaming"),
    SPORT_TYPE_AEROBICS_GYMS("Aerobics gyms"),
    SPORT_TYPE_GROUP_TRAINING("Group training"),
    SPORT_TYPE_CARDIO_BOXING("Cardio boxing"),
    SPORT_TYPE_MOUNTAINEERING("Mountaineering"),
    SPORT_TYPE_FENCING("Fencing"),
    SPORT_TYPE_SOFTBALL("Softball"),
    SPORT_TYPE_VOLLEYBALL("Volleyball"),
    SPORT_TYPE_ROLLING("Rolling"),
    SPORT_TYPE_PICKLE_BALL("Pickle ball"),
    SPORT_TYPE_TAEKWONDO("Taekwondo"),
    SPORT_TYPE_KARATE("Karate"),
    SPORT_TYPE_FLEXIBILITY("Flexibility"),
    SPORT_TYPE_ROWER("Rower"),
    SPORT_TYPE_JUMP_ROPE("Jump Rope"),
    SPORT_TYPE_STAIRS("Stairs"),
    SPORT_TYPE_CROSS_TRAINING("Cross Training");
    
    @NotNull
    private String type;

    SportsType(String str) {
        this.type = str;
    }

    @NotNull
    public final String getType() {
        return this.type;
    }

    public final void setType(@NotNull String str) {
        Intrinsics.checkNotNullParameter(str, "<set-?>");
        this.type = str;
    }
}
